serenity-bdd/serenity-core

- build.gradle
- core/build.gradle
- serenity-smoketests/build.gradle
- serenity-test-utils/build.gradle
Note that the failOnVersionConflict() added to top build now fails the build when dependency convergence problems exist.  This will keep the gradle build clean and alert to new dep problems.
I only processed core and cucumber modules.  Need to do rest of them - some of them probably fail with this.
With these and the cucumber module changes, the example pom builds clean of transitive dep problems (still catches on a duplicate classes issue across deps; probably need to config client module to ignore them).
> Updating core module for #16.

- core/build.gradle
core's version was 3.9.0.GA; reflections version is 3.12.1.GA
> Upgrade javassist version to match transitive dep. #16

- core/src/main/java/net/serenitybdd/core/pages/WidgetObject.java
- core/src/main/java/net/serenitybdd/core/pages/WidgetObjectImpl.java
- core/src/main/java/net/thucydides/core/annotations/locators/AbstractSingleItemHandler.java
- core/src/main/java/net/thucydides/core/annotations/locators/SmartAjaxElementLocator.java
- core/src/main/java/net/thucydides/core/annotations/locators/SmartElementHandler.java
- core/src/main/java/net/thucydides/core/annotations/locators/SmartElementLocatorFactory.java
- core/src/main/java/net/thucydides/core/annotations/locators/SmartFieldDecorator.java
- core/src/main/java/net/thucydides/core/annotations/locators/SmartListHandler.java
- core/src/main/java/net/thucydides/core/annotations/locators/SmartWidgetHandler.java
- core/src/main/java/net/thucydides/core/annotations/locators/SmartWidgetProxyCreator.java
- core/src/main/java/net/thucydides/core/annotations/locators/WebElementFacadeListItemHandler.java
- core/src/main/java/net/thucydides/core/annotations/locators/WidgetListItemHandler.java
- core/src/main/java/net/thucydides/core/guice/ThucydidesModule.java
- core/src/main/java/net/thucydides/core/webdriver/AbstractObjectInitialiser.java
- core/src/main/java/net/thucydides/core/webdriver/DefaultPageObjectInitialiser.java
- core/src/main/java/net/thucydides/core/webdriver/DefaultWidgetObjectInitialiser.java
- core/src/main/java/net/thucydides/core/webdriver/ElementLocatorFactorySelector.java
- core/src/main/java/net/thucydides/core/webdriver/WidgetProxyCreator.java
- core/src/test/java/net/serenitybdd/core/webdriver/integration/WhenBrowsingAWebSiteUsingWidgetObjects.java
- core/src/test/resources/static-site/index-widget-objects.html
WidgetObject: reusable page fragment with a nested search context implied by the Composition pattern.  This feature was requested here:
https://groups.google.com/forum/#!topic/thucydides-users/-SiQwD86W8I
https://groups.google.com/forum/#!topic/thucydides-users/01oNgOD9TnY
See attached unit tests for usage examples.
> feat: nested page objects i.e. widget objects

- build.gradle
- serenity-spring/src/main/java/net/serenitybdd/core/di/SpringDependencyInjector.java
- serenity-spring/src/test/groovy/net/serenitybdd/core/di/WhenInjectingSpringComponents.groovy
- serenity-spring/src/test/java/net/serenitybdd/core/di/samples/FlatScenarioStepsWithSpringContextHierarchyDependencies.java
- serenity-spring/src/test/java/net/serenitybdd/core/di/samples/FlatScenarioStepsWithSpringMetaAnnotationContextHierarchyDependencies.java
- serenity-spring/src/test/java/net/serenitybdd/core/di/samples/FlatScenarioStepsWithSpringMetaAnnotationDependencies.java
- serenity-spring/src/test/java/net/serenitybdd/core/di/samples/MetaContextConfiguration.java
- serenity-spring/src/test/java/net/serenitybdd/core/di/samples/MetaContextHierarchy.java
- serenity-spring/src/test/java/net/thucydides/junit/spring/samples/dao/HibernateUserDAO.java
These commits provide support for serenity-bdd/serenity-core#76.
Note that meta-annotation support for @ContextConfiguration and @ContextHierarchy was only introduced in spring 4.0, which necessitates a bump to the version of spring in use. However that bump has no impact on the existing production code base and only necessitates a simple change to HibernateTemplate use in HibernateDAO to handle the wildcard return type via an explicit unchecked cast.
> serenity-spring support for @ContextHierarchy and meta-annotations

- serenity-core/src/main/java/net/thucydides/core/webdriver/WebDriverFactory.java
DriverSources may implement some non-trivial logic, so it is very handy
for debugging to include in stack trace exception occurred while tried to
initialize new webdriver. Especially in multi-node test environment
configurations.
> fix: Improved error reporting for provided drivers

- serenity-demo/src/main/java/net/serenity_bdd/demo/steps/GoogleSearchSteps.java
GoogleSearchSteps.java:27: warning: [cast] redundant cast to GoogleHomePage
GoogleHomePage page = (GoogleHomePage) getPages().currentPageAt(GoogleHomePage.class);
GoogleSearchSteps.java:33: warning: [cast] redundant cast to GoogleResultsPage
GoogleResultsPage page = (GoogleResultsPage) getPages().currentPageAt(GoogleResultsPage.class);
> Fixing Java warnings - Redundant cast

- serenity-core/src/main/java/net/thucydides/core/reports/AcceptanceTestReporter.java
- serenity-core/src/main/java/net/thucydides/core/reports/ReportService.java
- serenity-core/src/main/java/net/thucydides/core/reports/TestOutcomeAdaptorReporter.java
- serenity-core/src/main/java/net/thucydides/core/reports/xml/XMLTestOutcomeReporter.java
When one of ddt parameters is null, we do not catch the exception(NullPointerException) and the process(create report) hangs.
The second thread is waiting creating report(waitForReportGenerationToFinish), but this will not happen.
> fix loop when parameter is null in ddt tests

- serenity-core/src/main/java/net/thucydides/core/reports/AcceptanceTestReporter.java
- serenity-core/src/main/java/net/thucydides/core/reports/xml/XMLTestOutcomeReporter.java
Before there was an compilation issue, in the module `serenity-junit`, as an Exception was not catched / rethrown (class: `net.thucydides.junit.runners.WhenGeneratingTestReports`).
Also it was not logical to throw an Exception, from the interface `net.thucydides.core.reports.AcceptanceTestReporter`. So changed it, to throw an IOException, as all underlaying implementations are all file based, an possibly can throw some IOException.
Only needed to fix, the implementation `net.thucydides.core.reports.xml.XMLTestOutcomeReporter` as otehr implementation did already only throw IOException.
> refactor: Corrects throwning of IOException, instead of Exception

- serenity-core/src/main/java/net/thucydides/core/webdriver/ProvidedDriver.java
- serenity-core/src/main/java/net/thucydides/core/webdriver/WebDriverFacade.java
- serenity-core/src/test/java/net/thucydides/core/webdriver/WhenUsingAProvidedDriver.java
Better way to fix THUCYDIDES-253. The method that checks if the driver is javascript enabled looks at the driver class returned from WebDriverFacade and in the case, it will see that ProvidedDriver implements JavascriptExecutor but when it tries to execute javascript on the proxied driver that does not necessarily have to implement JavascriptExecutor, then it can throw an exception. This proposed fix checks if the driverclass in the WebDriverFacade is a provided driver, if it is, then the correct driver class it should look at is contained in the proxied driver.
> Better way to fix THUCYDIDES-253

- serenity-core/src/test/java/net/thucydides/core/steps/WhenRecordingStepExecutionResults.java
This pull request contains:
updating of one test, witch should be updated after this [commit](https://github.com/serenity-bdd/serenity-core/commit/8fedb5437877646684a733cd134427652f9b19ad)
Problem was with updating BaseStepListener, and it internal usage of ThucydidesWebDriverManager. Some of tests fail because of not-initialized browser during test init.
Solution - change way for initializing ThucydidesWebDriverManager by using ThucydidesWebDriverSupport.
> Pull request for updating test in serenity_core (ThucydidesWebDriverSupport init)

- serenity-core/src/main/java/net/thucydides/core/webdriver/SystemPropertiesConfiguration.java
- serenity-gradle-plugin/build.gradle
- serenity-gradle-plugin/src/test/groovy/net/serenitybdd/plugins/gradle/WhenUsingTheGradlePlugin.groovy
- serenity-gradle-plugin/src/test/groovy/net/serenitybdd/plugins/gradle/integration/WhenRunTestsWithGradlePlugin.groovy
- serenity-gradle-plugin/src/test/resources/test-retries-gradle-project/build.gradle
- serenity-gradle-plugin/src/test/resources/test-retries-gradle-project/settings.gradle
- serenity-gradle-plugin/src/test/resources/test-retries-gradle-project/src/test/java/serenity/example/AuthorizationSteps.java
- serenity-gradle-plugin/src/test/resources/test-retries-gradle-project/src/test/java/serenity/example/WhenAuthorisationPerforming.java
- serenity-junit/src/main/java/net/serenitybdd/junit/runners/SerenityRunner.java
- serenity-junit/src/test/java/net/serenitybdd/junit/runners/integration/WhenRetryingFailedTests.java
- serenity-junit/src/test/java/net/serenitybdd/junit/runners/integration/WhenRunningADataDrivenTestScenario.java
- serenity-smoketests/src/test/resources/serenity.conf
#132 issue:
reported incorrect behaving during providing *max.retires* property.
Problem was in allowing using retrying test methods in SerenityRunner without *junit.retry.tests* property. As result every retry new RunNotifier was created, ans this produce issue. 
Additional check was added to RunNotifier to ignore max.retries property if *unit.retry.tests* property not provided or not equal to *true*
Also added 3 additional tests to emulate this problems.
> Pull request for #132 issue

- serenity-rest-assured/src/main/java/net/serenitybdd/rest/SerenityRest.java
- serenity-rest-assured/src/test/groovy/net/serenitybdd/rest/integration/WhenRunningHttpsRestTestsThroughSerenity.groovy
**Problem:**
In #128 reported: During usage SerenityRest for testing rest API by HTTPS protocol - response and status doesn't available in Serenity Aggregation report
**Reason:**
According to [RFC1341](http://tools.ietf.org/html/rfc1341) Content type [can contains](http://www.w3.org/Protocols/rfc1341/4_Content-Type.html) optional parameter after sub-type. Our code not ready for it. 
**Solution:**
Updated method for checking if response body suitable for recording, based on ContentType. Also added additional test where GET request using HTTPS is send to github and checks id of current repo. [Limits](https://developer.github.com/v3/#rate-limiting) for requests without auntification 60 per hour, it should be enough
> Pull requst for fixing #128 issue

- serenity-smoketests/src/test/java/net/serenitybdd/demos/todos/features/filter_my_todos/FilterTodosByStatus.java
- serenity-smoketests/src/test/resources/serenity.conf
**Problem:**
during run smoke-tests with enabling retries - ant build fail
**Reason:**
when some test method fail and call of it retired - ant/gradle/mvn builds fails, because actually some methods are fail, and reports will contain same method fired several time - some failed, and last green. Serenity report will contains correct information, about actual result for testing. If same method will be run several times because of fail and on lat one try this test method will run successful - this test in serenity report will be green
**Solution:**
disabling retrying in smoke-tests and disabling methods prepared for "first run fail, second successful" (test case for retrying logic)
> Pull request for desabling retries in smoke-tests

- serenity-gradle-plugin/src/main/groovy/net/serenitybdd/plugins/gradle/SerenityPlugin.groovy
- serenity-gradle-plugin/src/test/groovy/net/serenitybdd/plugins/gradle/WhenUsingTheGradlePlugin.groovy
Problem:
Issue  #130 was returned, reports collects, but in default directory, not in serenity.outputDirectory
Reason:
It seams that some values aren't read from sererenity.properties, and because of way of tasing gradle builds under 2.5 builds - I miss it. 
Solution:
Read serenity.properties file as Property file. Updated test for emulating such behaving. This pull request depends on #181 - because it fix general build fail of master.
> 130_issue: reading serenity.properties fix. 

- serenity-core/src/test/groovy/net/serenitybdd/core/photography/integration/WhenAPhotographerTakesScreenshots.groovy
Problem:
null pointer during execution quit for webDriver
Reason: 
sometimes this test fail, and driver equal to null.
Solution:
Added additional check before cleanup. If webDriver equal to null - it means that nothing to clean.
> Pull request for adding photographer test fix

- serenity-core/src/main/java/net/thucydides/core/steps/BaseStepListener.java
Here is update for constructor of Base Step Listener. 
Purpose of this update - reduce code duplication: existed constructor with same logic was reused.
> Pull requst for minor Base Step Listener Constructor update

- serenity-core/src/main/java/net/serenitybdd/core/photography/bluring/Blurer.java
- serenity-core/src/main/java/net/serenitybdd/core/photography/resizing/Resizer.java
- serenity-core/src/main/java/net/thucydides/core/images/ResizableImage.java
- serenity-core/src/main/java/net/thucydides/core/pages/components/FileToDownload.java
- serenity-core/src/main/java/net/thucydides/core/reflection/ClassFinder.java
- serenity-core/src/main/java/net/thucydides/core/requirements/model/NarrativeReader.java
- serenity-core/src/main/java/net/thucydides/core/screenshots/ScreenshotDigest.java
- serenity-core/src/main/java/net/thucydides/core/util/PropertiesFileLocalPreferences.java
- serenity-core/src/main/java/net/thucydides/core/util/VersionProvider.java
Problem:
During investigation for issue #160 I found a lot of places, where we should close streams properly. It can be reason of this issue, or not - I cant reproduce it. 
Reason: 
It seems that some resources are not deallocated in properly way. 
Solution:
some try-catch-finally replaced by try-catch resources, also added closing resources during reading properties and zip files.
> Pull requst for adding input streams closing. Please don't merge if not success

- serenity-core/src/main/java/net/serenitybdd/core/rest/RestMethod.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/SerenityRest.java
- serenity-rest-assured/src/test/groovy/net/serenitybdd/rest/integration/WhenRunningRestTestsThroughSerenity.groovy
**Problem**
in #184 issue reported that in REST-assured PATCH requests are not logged in serenity report
**Reason**
not implemented
**Solution**
updated implementation for logging. Added tests for this type of request.
> Pull requst for 184_issue: logging for PATCH operation added

- serenity-core/src/test/groovy/net/serenitybdd/core/photography/integration/WhenAPhotographerTakesLotsOfScreenshots.groovy
Problem:
During investigation reason of #173 was found error - these tests not fail even if dirs not exists. These test should fail in same time as WhenAPhotographerTakesScreenshots tests
Reason:
We should check amount of screenshots that exists
Solution:
updated way of checking if all screenshots exists in collections.
> Pull requst for updating tests for screenshots

- build.gradle
This fixed the problem described at https://groups.google.com/forum/#!topic/thucydides-users/AsdBfFV8qHc.
```
+--- net.serenity-bdd:serenity-core:1.1.21
|    |    +--- com.google.guava:guava:18.0
|    |    +--- com.google.inject:guice:3.0
|    |    |    +--- javax.inject:javax.inject:1
|    |    |    +--- aopalliance:aopalliance:1.0
|    |    |    \--- org.sonatype.sisu.inject:cglib:2.2.1-v20090111 -> cglib:cglib:3.1
|    |    +--- cglib:cglib:3.1
```
> fix: cglib dependency conflict from guice

- serenity-rest-assured/src/main/java/net/serenitybdd/rest/SerenityRest.java
Problem: 
in #197 issue was reported about problems of logging rest request body if source not string but map for example
Reason:
It seems that we call toString() and that's all - as result objects appeared in serenity logs not like Json/xml but string. 
Solution:
Rewriting mechanism of serializing  to take content type from current request and serialize input according to contentType from input object. Tests aren't provided, in current structure very hard test testOutcome under serenity-rest-assured module - all tested manually.
> Pull request for updating SerenityRest to log all types of input

- serenity-rest-assured/src/main/java/net/serenitybdd/rest/SerenityRest.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/decorators/AuthenticationSpecificationWrapper.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/decorators/BaseWrapper.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/decorators/PreemptiveAuthSpecWrapper.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/decorators/RequestLogSpecificationWrapper.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/decorators/RestDecorator.java
- serenity-rest-assured/src/test/groovy/net/serenitybdd/rest/WhenExecutingWrappedMethods.groovy
Problem:
in #212 and #185 was reported about impossibility usage of log() and auth() and auntificate() methods of serenity-rest-assured
Reason:
We use enhancements of RequestSpecification methods to record calls of them. We "wrap" all method  to be notified about it call, but during log and auth RequstSpecification returned without provided wrappers. This was not tested at all. 
Solution: 
Providing wrappers for AuthenticationSpecification and RequestLogSpecification to be sure that they will operate with enhancemened RequestSpecification. Also some tests are provided.
> Pull request  for adding log and auth wrappers for serenity-rest-assured

- serenity-junit/src/test/groovy/net/thucydides/junit/runners/WhenRunningTestScenarios.groovy
- serenity-junit/src/test/java/net/serenitybdd/junit/runners/integration/WhenRunningADataDrivenTestScenario.java
Problem:
in #223 reported that some how WhenRunningADataDrivenTestScenario fails sometime
Reason:
I can't reproduce it on my pc, but it can be reproduced on CI. 
Solution:
It can be issue with filtering files in directory, that created before adding files to it. This is experimental fix, and should be rollbacked if issue with this test will appear in future.
> Pull request for adding reloading output dir before checks in tests

- serenity-core/build.gradle
Upgrades type.safe dependency 
Now it is possible to use [ConfigBeanFactory](https://github.com/typesafehub/config#configbeanfactory)
In compiling new classes will be available, also build should be successful
N/A
N/A
#243  
N/A
> #243 Upgrading typesafe.config from 1.2 to 1.3

- serenity-core/src/main/java/net/thucydides/core/ThucydidesSystemProperty.java
- serenity-core/src/main/java/net/thucydides/core/bootstrap/ThucydidesContext.java
- serenity-core/src/main/java/net/thucydides/core/reports/ReportService.java
- serenity-junit/src/main/java/net/serenitybdd/junit/runners/SerenityParameterizedRunner.java
- serenity-junit/src/main/java/net/serenitybdd/junit/runners/SerenityRunner.java
Adds "report" with actual properties used in configuration during execution of tests
Now it is possible get information what properties are used during creating test reports in Junit. Will be used to add more properties to analyze of test results. Also it will be possible to turn it off in some nearest future. 
Project with JUnit tests and Serenity BDD should be compiled, in target folder (target for reports) file with name "serenity.configuration.json" will appear. In this file should be valid json with path to target directory used during test execution
N/A
will be created under issue serenity-bdd/serenity-documentation/issues/50
N/A
N/A
> Report for configuration

- serenity-gradle-plugin/src/main/groovy/net/serenitybdd/plugins/gradle/SerenityPlugin.groovy
- serenity-gradle-plugin/src/main/groovy/net/serenitybdd/plugins/gradle/SerenityPluginExtension.groovy
- serenity-gradle-plugin/src/test/groovy/net/serenitybdd/plugins/gradle/WhenUsingTheGradlePlugin.groovy
- serenity-junit/src/test/groovy/net/thucydides/junit/runners/WhenRunningTestScenarios.groovy
Updates gradle plugin to use same Configuration. It is part of fix for issue #183. 
Behaving will not change
Build some project with custom serenity.outputDirectory. Reports should be under outputDir
One test marked as @Ignore. It should be upgraded to use gradle 2.10 for executing external projects.
N/!
#183
N/A
> Updating of gradle plugin to use same Configuration as SerenityRunner

- serenity-core/build.gradle
Reverts serenity-bdd/serenity-core#248, because 1.3 can be used only with java 8, and some of our users are use java 7.
> Revert "#243 Upgrading typesafe.config from 1.2 to 1.3"

- build.gradle
- serenity-core/src/main/java/net/thucydides/core/steps/FilePathParser.java
- serenity-core/src/main/java/net/thucydides/core/util/PropertiesFileLocalPreferences.java
- serenity-core/src/main/java/net/thucydides/core/webdriver/SystemPropertiesConfiguration.java
- serenity-core/src/test/java/net/thucydides/core/webdriver/WhenObtainingTheOutputDirectory.java
- serenity-gradle-plugin/build.gradle
- serenity-gradle-plugin/src/main/groovy/net/serenitybdd/plugins/gradle/SerenityPlugin.groovy
- serenity-gradle-plugin/src/test/groovy/net/serenitybdd/plugins/gradle/WhenUsingTheGradlePlugin.groovy
- serenity-junit/src/test/groovy/net/thucydides/junit/runners/WhenRunningTestScenarios.groovy
Update core to fix problems with multimodule projects with mvn and gradle. Enabling parallel execution of tests for all modules. Updated build dependency for maven-gradle-plugin.
One level projects
App
src
Multimodule projects
App
child1
src
child2
src
Before this fix mvn/gradle if build executed from root dir (App):
1) used serenity.properties from App dir
2) generated incorrect reports
Before this fix mvn/gradle if build executed from module dir (child1 or child2):
1) used serenity.properties from child dir
2) generated correct reports
After this fix mvn/gradle if build executed from root dir (App):
1) used serenity.properties from child dir (during execution of child)
2) generate reports in child dir
After this fix mvn/gradle if build executed from module dir (child1 or child2):
1) …
> Updating core to support report generation for multimodule projects with gradle/mvn

- serenity-core/src/main/java/net/thucydides/core/steps/AnnotatedStepDescription.java
- serenity-core/src/main/java/net/thucydides/core/steps/ExecutedStepDescription.java
- serenity-core/src/main/java/net/thucydides/core/steps/StepInterceptor.java
- serenity-core/src/test/java/net/thucydides/core/steps/WhenDescribingSteps.java
- serenity-core/src/test/java/net/thucydides/core/steps/WhenDescribingStepsUsingAnnotations.java
- serenity-junit/src/test/java/net/serenitybdd/junit/runners/integration/WhenRunningANonWebTestScenario.java
- serenity-junit/src/test/java/net/thucydides/samples/NonWebTestScenarioWithParameterizedSteps.java
- serenity-junit/src/test/java/net/thucydides/samples/SampleNonWebSteps.java
The goal of this change is to fix problem with wrong step title displayed in the generated HTML-report in case if the method parameter contains comma character.
As far as I understood currently information about method name and its parameters is stored as string value (StepInterceptor#testNameWithArguments) and later there is an attempt to restore information about arguments by splitting this string by delimiter character (AnnotatedStepDescription#annotatedStepNameWithParameters). The problems appears when some parameter contains delimiter character and it leads to wrong splitting. 
One of possible way to solve the problems was encoding of delimiter character inside method parameters, but there may be some problems with extracting them (especially taking into account that the description …
> #268 Fix issue with custom step name when a method parameter contains with comma

- serenity-gradle-plugin/src/main/groovy/net/serenitybdd/plugins/gradle/SerenityPlugin.groovy
Moving the definition of reportDirectory in order to allow easy configuration through the serenity configuration block. Currently this directory gets set when applying the plugin, which makes it only possible to change through setting an environment variable at the same level as applying the plugin. For multi-module projects with compile dependencies, setting this on a module basis does not work without making it part of the task.
This now allows for configuration per service to do something like:
serenity {
reportDirectory "/dev/multi-module-project/test-output/integrationTest/${project.name}"
}
> Moving definition of reportDirectory to within the tasks

- serenity-core/src/main/java/net/thucydides/core/webdriver/capabilities/BrowserStackRemoteDriverCapabilities.java
Update processing of "browserstack.os.version" and "browserstack.browser.version" system properties
Currently BrowserStack requires to use "os_version" and "browser_version" capabilities to define OS and browser version. Serenity sends these parameter with "." as a separator (as it was required previously). This PR changes processing of two system parameters to follow updated BrowserStack parameter syntax.
There are no ready tests because it requires providing credentials for BrowserStack. The fix was tested locally.
No.
The fix was implemented in the way that doesn't affect existing Serenity configuration parameters. No need to reflect in the documentation.
https://github.com/serenity-bdd/serenity-core/issues/276
No.
> Updated processing of system properties for OS and browser versions for BrowserStack

- serenity-core/src/main/java/net/serenitybdd/core/buildinfo/PropertyBasedDriverCapabilityRecord.java
- serenity-core/src/main/java/net/thucydides/core/images/ResizableImage.java
- serenity-core/src/main/java/net/thucydides/core/reports/MultithreadExecutorServiceProvider.java
- serenity-core/src/main/java/net/thucydides/core/reports/ReportService.java
- serenity-core/src/main/java/net/thucydides/core/reports/csv/CSVReporter.java
- serenity-core/src/main/java/net/thucydides/core/reports/html/Formatter.java
- serenity-core/src/main/java/net/thucydides/core/reports/html/HtmlAggregateStoryReporter.java
- serenity-core/src/main/java/net/thucydides/core/resources/FileResources.java
- serenity-core/src/main/java/net/thucydides/core/steps/stepdata/CSVTestDataSource.java
- serenity-core/src/main/java/net/thucydides/core/util/PropertiesFileLocalPreferences.java
- serenity-core/src/test/groovy/net/thucydides/core/reports/csv/WhenSavingTestOutcomesInCSVForm.groovy
- serenity-core/src/test/java/net/thucydides/core/util/WhenLoadingPreferencesFromALocalPropertiesFile.java
Updates way of waiting generated reports. Also code updated to use java-core enums instead of same from google, and updated way of closing opened streams. Updated code that prints to System.err to logging with error level. Updated default config of cores witch are used during report generation to be dependent on cpu configuration. 
Tests should became stable and do not fail "time to time" because of abscond reports/screenshots 
Behaving should not change
N/A
N/A
#173
N/A
> Updating of report generation engine to wait for started threads, and close all opened streams

- build.gradle
Updating dependency for using in serenity modules
Will be used commons-collections:commons-collections:3.2.2 instead of 3.2.1 as in selenium 2.50.1. 
This was done for serenity modules (jira, cucumber, etc.)
N/A
N/A
N/A
N/A
N/A
> Updating dependency for using in serenity modules

- serenity-core/src/main/java/net/thucydides/core/requirements/RequirementPersister.java
Updated RequirementPersister
Will not throw exception during loading json requirements if gson can not be read (and google gson lib returned null as expected)
All tests should be fine
N/A
N/A
N/A
N/A
> Updated RequirementPersister

- .gitattributes
Updating gitattributes not to update chromedriver and woff files
> Updating gitattributes not to update chromedriver and woff files

- serenity-core/src/main/java/net/thucydides/core/webdriver/ThucydidesWebdriverManager.java
- serenity-core/src/test/groovy/net/serenitybdd/core/webdriver/WhenUsingWebDriverFacade.groovy
Updating ThucydidesWebDriverSupport.getSessionId() to work properly with remote drivers 
If remote driver is used ThucydidesWebDriverSupport.getSessionId() should return session for it (if defined)
You can create some tests using Saucelabs as described under  #299
N/A
N/A
#299 
N/A
> Updating ThucydidesWebDriverSupport.getSessionId() to work properly with remote drivers

- serenity-gradle-plugin/src/main/groovy/net/serenitybdd/plugins/gradle/SerenityPlugin.groovy
Updates gradle plugin to work with multimodule projects.  
Reports should generate in correct dirs (relative to module dirs but not to root project dir) and serenity-properties should be taken from module dirs. 
Some project with multimodules should be created, and gradle test aggregate should be executed against it. 
system property "project.build.directory" is used. Should not broke anything. 
N/A
N/A
N/A
> Gradle plugin update

- serenity-core/src/main/java/net/thucydides/core/requirements/FileSystemRequirementsTagProvider.java
- serenity-core/src/main/java/net/thucydides/core/webdriver/SystemPropertiesConfiguration.java
- serenity-gradle-plugin/src/main/groovy/net/serenitybdd/plugins/gradle/SerenityPlugin.groovy
Updating requirements location
Requirements can be in sumodule directory as well as in working directory
Some project with multi module structure should be created and run with gradle or maven plugin. 
N/A
N/A
#305, serenity-bdd/serenity-maven-plugin/issues/22
> Updating requirements location to use sumodule directory for multimodule projects

- serenity-report-resources/src/main/resources/freemarker/default.ftl
Adds a default empty string "" into default.ftl template file to avoid crashing when a fileName is not provided for a function within the error stacktrace.
Adds a newline br tag into the stacktrace dialog, till now there were occasions where multiple functions fit on a single line.
Should prevent failure when a call in the stacktrace does not have an associated fileName. 
Recreate an identical stack to #312. 
No.
Not user facing and no new behavior.
#312 
Before:
After:
Error:
> #312 On Test Failure stacktrace can contain elements with no fileName (default.ftl)

- serenity-core/src/main/java/net/thucydides/core/ThucydidesSystemProperty.java
- serenity-core/src/main/java/net/thucydides/core/reflection/StackTraceAnalyser.java
- serenity-core/src/main/java/net/thucydides/core/reports/adaptors/specflow/ScenarioSplitter.java
- serenity-core/src/main/java/net/thucydides/core/reports/html/HtmlAcceptanceTestReporter.java
- serenity-core/src/main/java/net/thucydides/core/reports/junit/JUnitXMLOutcomeReporter.java
- serenity-core/src/main/java/net/thucydides/core/requirements/FileSystemRequirementsTagProvider.java
- serenity-core/src/main/java/net/thucydides/core/requirements/PackageAnnotationBasedTagProvider.java
Updated lines where "is empty" string condition used from value!=null to StringUtils.isNotEmpty(value)
If some property are not provided it means that they can be "" or null. So this improvenment will mark strings with value "" as empty
All should work as before 
Warn of legacy properties  should disappear (if you don't use them) 
N/A
#310
N/A
> Updated checking of empty string to use StringUtils, for #310

- serenity-core/build.gradle
- serenity-core/src/main/java/net/thucydides/core/reports/AcceptanceTestLoader.java
- serenity-core/src/main/java/net/thucydides/core/reports/ReportLoadingFailedError.java
- serenity-core/src/main/java/net/thucydides/core/reports/ReportService.java
- serenity-core/src/main/java/net/thucydides/core/reports/TestOutcomeLoader.java
- serenity-core/src/main/java/net/thucydides/core/reports/json/JSONTestOutcomeReporter.java
- serenity-core/src/main/java/net/thucydides/core/reports/junit/JUnitXMLOutcomeReporter.java
- serenity-core/src/main/java/net/thucydides/core/reports/xml/XMLTestOutcomeReporter.java
- serenity-core/src/test/groovy/net/thucydides/core/reports/WhenProcessingTestOutcomes.groovy
- serenity-core/src/test/groovy/net/thucydides/core/reports/WhenWritingAndReadingTestOutcomes.groovy
Updated loader and reporter to load and generate testoutcomes concurrently, add tests for checking if reports can be generated and loaded in series, updated gson core to 2.4.
Here is test that should be successful if loaders and reports can work concurrently, some bugs already fixed in gson lib so it was updated. Also loader now can be executed concurrently as well. 
Some test project with very fast tests should be created. After executing goals "test aggregate" report should contains all tests. 
N/A
N/A
serenity-bdd/serenity-jbehave/issues/45, #322 
N/A
> Updated loader and reporter to load and generate testoutcomes concurrently with tests, updated gson core to 2.4

- serenity-core/src/main/java/net/thucydides/core/reports/json/JSONTestOutcomeReporter.java
- serenity-core/src/main/java/net/thucydides/core/reports/junit/JUnitXMLOutcomeReporter.java
- serenity-core/src/main/java/net/thucydides/core/reports/xml/XMLTestOutcomeReporter.java
Updated report generation to use temp files.
It seems that reporters in different runtime can rewrite same file, as result some artefacts can appear in the end or in the beginning for file. To avoid such behaving temporary files are used during generation of file, and after that report file renamed according expectation. 
Some project with a lot of tests with fast tests should be created, and tests should be executed in parallel several times. All tests should be included in aggregated report every time. 
N/A
N/A
#322, serenity-bdd/serenity-jbehave/issues/45
N/A
> Updated report generation to use temp files.

- serenity-core/src/main/java/net/thucydides/core/model/stacktrace/FailureCause.java
- serenity-core/src/test/java/net/thucydides/core/model/stacktrace/FailureCauseNoMsgException.java
- serenity-core/src/test/java/net/thucydides/core/model/stacktrace/FailureCauseTest.java
Updates report to include exception/assertion message
If assertion fire with some message - it should appear in serenity report
Using serenity bdd some test with 
```
org.junit.Assert.assertTrue("this message should be visible", false);
```
should be executed - in reports such message must be visible
N/A
N/A
#321 
N/A
> Included exception/assertion message into serenity report

- serenity-core/src/main/java/net/thucydides/core/webdriver/appium/AppiumConfiguration.java
- serenity-core/src/test/groovy/net/thucydides/core/webdriver/appium/WhenConfiguringAnAppiumDriver.groovy
Appium 1.5 was released last week, and the initialization code has been refactored.  The way Serenity setups up its own Appium driver requires both browsername and app to be supplied.  This is no longer compatible with Appium.
> appium.app is no longer required if appium.browserName is supplied

- serenity-core/src/main/java/net/thucydides/core/util/NameConverter.java
- serenity-core/src/test/java/net/thucydides/core/util/WhenMakingTestNamesMoreReadable.java
Updated name processing of test
If mothod contains CSV JSON XML this abbreviations will not be changed
`TestCaseForCSVFormat` will be transformed to `Test case for CSV format`
Some test class or test method should be created with CSV or JSON or XML in name and executed. Also aggregation report should be created. 
N/A
N/A
#215
> Updated processing of names to keep abbreviations of JSON CSV XML

- serenity-core/src/main/java/net/thucydides/core/reports/json/JSONTestOutcomeReporter.java
- serenity-core/src/main/java/net/thucydides/core/reports/junit/JUnitXMLOutcomeReporter.java
- serenity-core/src/main/java/net/thucydides/core/reports/xml/XMLTestOutcomeReporter.java
Updated moving files. 
Processing of tmp files for reports should work properly on windows
Simple build should be run on Windows
N/A
N/A
#334
N/A
> Updated moving files. Now tmp files of reports will be moved only after stream will be closed

- serenity-core/src/main/java/net/thucydides/core/reports/json/JSONTestOutcomeReporter.java
- serenity-core/src/main/java/net/thucydides/core/reports/json/gson/GsonJSONConverter.java
- serenity-core/src/main/java/net/thucydides/core/reports/xml/XMLTestOutcomeReporter.java
triggered by https://github.com/serenity-bdd/serenity-cucumber/issues/41
> Updated story/load of outcomes - serenity.report.encoding property will be used with UTF-8 as default 

- serenity-junit/src/main/java/net/serenitybdd/junit/runners/ParameterizedTestsOutcomeAggregator.java
- serenity-junit/src/main/java/net/serenitybdd/junit/runners/QualifiedTestsRunner.java
- serenity-junit/src/main/java/net/serenitybdd/junit/runners/TestClassRunnerForInstanciatedTestCase.java
- serenity-junit/src/main/java/net/serenitybdd/junit/runners/TestClassRunnerForParameters.java
- serenity-junit/src/test/groovy/net/serenitybdd/junit/finder/WhenRunningADataDrivenTestScenarioWithQualifier.groovy
- serenity-junit/src/test/java/net/thucydides/samples/SampleDataDrivenScenarioWithQualifier.java
Updated processing of @Qualifier tag in junit tests with data tables. Now it is possible add short description to steps based on parameters value
public method with annotation @Qualifier will be used to determine correct step name for test in aggregation report. 
You can use such test class: 
```
@RunWith(SerenityParameterizedRunner.class)
public class SampleDataDrivenScenarioWithQualifier {
@TestData
public static Collection testData() {
return Arrays.asList(new Object[][]{
{"a", 1},
{"B", 2},
{"c", 3},
{"D", 4},
{"e", 5},
{"F", 6},
{"g", 7},
{"h", 8},
{"i", 9},
{"j", 10},
{"k", 11},
{"l", 12},
});
}
private String option1;
private Integer option2;
public SampleDataDrivenScenarioWithQualifier(String option1, Integer option2) {
this.option1 = option1;
this.option2 = option2;
}
@Qualifier …
```
> Updated processing of @Qualifier tag in junit tests with data tables. Now it is possible add short description to steps based on parameters value

- serenity-core/src/main/java/net/thucydides/core/model/TestOutcome.java
- serenity-junit/src/test/groovy/net/serenitybdd/junit/finder/WhenRunningADataDrivenTestScenarioWithGivenWhenThenSteps.groovy
- serenity-junit/src/test/java/net/thucydides/samples/SampleDataDrivenScenarioWithQualifier.java
Updated scenario data driven steps processing for report - now report will contains steps as for first scenario
For data driven junit test scenario in report will contains steps from first test case. For example: 
```
@Test
public void happy_day_scenario() {
steps.GivenSomeParameter(option1, option2);
steps.WhenDoingSome(option1, option2);
steps.ThenShouldBeNext(option1, option2);
}
```
will appear as 3 steps on scenario
You can create data driven test and steps used in test will be included in report under scenario as 3 steps
N/A
serenity-documentation/issues/63
#338 
before: 
after:
> Updated scenario data driven steps processing for report - now report will contains steps as for first scenario

- serenity-core/src/main/java/net/thucydides/core/webdriver/WebDriverFacade.java
Fixed issue with closing web driver initialized with appium
Before closing webdriver we trying to get windows handles, but this function throw exception for Android devices, because it is still not implemented (works fine for iOS). So before getting window handles we should check if Android is used. 
Any tests should be created, with using appium and android
N/A
N/A
#359 
N/A
> Fixed closing web driver when appium is used, it seems that window handles still does not implemented for Android devices, only for iOS

- serenity-core/src/main/java/net/serenitybdd/core/photography/PageSourceRecorder.java
- serenity-core/src/main/java/net/serenitybdd/core/photography/PhotoSession.java
- serenity-core/src/main/java/net/thucydides/core/webdriver/WebDriverFactory.java
- serenity-core/src/test/groovy/net/serenitybdd/core/photography/WhenTakingScreenshotsFromDiedBrowser.groovy
Updaing making screenshort with died browser - nothing should be taken  
If screen shots or page sources tried to be taken with died browser - they should be absent 
N/A
If browser died, and testFailed reported - during reporting screenshot is taken - it this situation screenshot or page source should be empty
N/A
#363 
before fix: 
after fix:
> Updated making screenshort with died browser - nothing should be taken

- serenity-core/src/main/java/net/thucydides/core/ThucydidesSystemProperty.java
- serenity-core/src/main/java/net/thucydides/core/statistics/service/FeatureStoryTagProvider.java
- serenity-core/src/test/groovy/net/thucydides/core/reports/WhenManagingTestResultTags.groovy
- serenity-core/src/test/groovy/net/thucydides/core/reports/adaptors/specflow/WhenLoadingSpecflowLogOutputAsTestOutcomes.groovy
- serenity-core/src/test/groovy/net/thucydides/core/reports/json/WhenStoringTestOutcomesAsJSON.groovy
- serenity-core/src/test/groovy/net/thucydides/core/tags/WhenFindingTestOutcomeTags.groovy
https://github.com/serenity-bdd/serenity-jbehave/issues/17
FeatureStoryTagProvider causes the story duplicated in report home if story title differs from filename. 
FeatureStoryTagProvider is legacy code to support the @Feature annotation
When setting the property use.test.case.for.story.tag = false , there will be no story tags defined by this tag provider for the test cases.
> set property "use.test.case.for.story.tag = false" by default

- serenity-report-resources/src/main/resources/freemarker/default.ftl
Updated rest report template to make it more user-friendly 
Exclude cookies if they are the same for request and response, change position of these fields. 
Some test with rest should be created
N/A
N/A
#384
> Updated rest report template

- serenity-core/src/main/java/net/thucydides/core/webdriver/WebDriverFactory.java
- serenity-core/src/test/groovy/net/serenitybdd/core/photography/WhenTakingScreenshotsFromDiedBrowser.groovy
Fixed isAlive function to work with appium
It is possible that drover closed during test execution (some error for example). This function helps Serenity reinit driver in this case. 
You can test with some other driver - firefox or chrome, for this you should create test class with multiple test cases (web tests), run it and after some of test opens browser - close it. Only current test should fail, other tests should be fine
N/A
If the pull request is user facing, how is it documented?
Are there examples of how to use the new behavior that users need to know about?
#408
N/A
> Fixed isAlive function to work with appium

- serenity-core/build.gradle
Appium's java client 3.4 was released behind Appium 1.5, but was intended to be paired.  By.name locator for apps has been deprecated, but this shouldn't be a breaking change yet.
Release notes:
https://discuss.appium.io/t/java-client-version-3-4-0-released/8961
https://discuss.appium.io/t/java-client-version-3-4-1-released/9416
> Updated appium java client to version 3.4.1

- serenity-core/src/main/java/net/thucydides/core/matchers/BeanMatcherAsserts.java
- serenity-core/src/test/java/net/thucydides/core/matchers/WhenMatchingPropertyValueCollections.java
- serenity-core/src/test/java/net/thucydides/core/matchers/WhenMatchingPropertyValuesWithMaps.java
Add shouldNotMatch(List<T> items, BeanMatcher... matchers) method into BeanMatcherAsserts 
A user now has an ability to assert that matched element is not present in collection
The implementation is straightforward and Unit Tests written cover all required functionality of method added and also provide an example of new method usage.
Existing code was not changed in any way so there are no any side effects
Probably documentation section "8.8. Using Fluent Matcher expressions" should be updated to provide example of usage, e.g. 
```
@Step
public void should_not_see_artifacts_where(BeanMatcher... matchers) {
shouldNotMatch(onSearchResultsPage().getSearchResults(), matchers);
}
```
#453
> Add ability to assert that matched element is not present in collection (#453)

- serenity-rest-assured/src/main/java/net/serenitybdd/rest/utils/RestReportingHelper.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/utils/RestResponseRecordingHelper.java
- serenity-rest-assured/src/test/groovy/net/serenitybdd/rest/WhenRecordPostRequestsWithSerenityRest.groovy
Fix for Rest-Assured Integration:
Fix two issues with report generation for REST Query responses
1. Now user has ability to see response body for responses with  HTML content type in report
2. Cookies field of Rest Query element in report now doesn't contain headers
Fix can be tested by performing post request with arbitrary post data using Rest-Assured integration to the following URL:
http://www.angularjshub.com:80/code/examples/servercalls/01_HTTPService/server.php?param1=first%20param&param2=second%20param
After that report should be generated and tester make sure that the report contains Response Body and the Cookies field is empty. Also, unit tests were written to cover changed functionality
There are no sideffects
Documentation update is not needed
#448
> Add ability to see response body for responses with  HTML content type in report

- serenity-rest-assured/src/main/java/net/serenitybdd/rest/decorators/request/RequestSpecificationParametersConfigurations.java
simple parameters should be serialised as simple parameters not as array
simple parameters should be serialised as simple parameters not as array
next code should be used: 
```
import static net.serenitybdd.rest.SerenityRest.*;
...
given()
.param("param", "asasas")
.log().all()
.post("server.php");
...
```
N/A
N/A
#444 
N/A
> In Serenity rest fixed params wrapping

- serenity-browsermob-plugin/src/main/java/net/thucydides/browsermob/fixtureservices/BrowserMobFixtureService.java
Browsermobproxy tries to validates certificates by default, which is at odds with Selenium's default behaviour of ignoring invalid certificates.  I've tried to build on top of the existing refuse.untrusted.certificates property to make this optional.
It would be good if someone could review this, as I have had troubles getting Serenity to build locally, and whether untrusted.certificates would be a better candidate to hook into.
The end game is to be able to attach a proxy to a site being tested when access via HTTPS with a self signed certificate.
> Made it possible to ignore invalid certificates when using BrowserMobProxy

- serenity-core/src/main/java/net/thucydides/core/ThucydidesSystemProperty.java
- serenity-core/src/main/java/net/thucydides/core/webdriver/strategies/InternetExplorerDriverBuilder.java
This PR provides support for new **webdriver.ie.driver** property. Some details:
- Without this feature, If IE driver is not on the path then an exception like the following is thrown: 
```
Sep 20, 2016 3:56:40 PM org.openqa.selenium.safari.SafariDriverServer start
INFO: Server started on port 32491
Sep 20, 2016 3:56:43 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Shutting down
Sep 20, 2016 3:56:43 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Stopping server
Sep 20, 2016 3:56:43 PM org.openqa.selenium.safari.SafariDriverServer stop
INFO: Stopping server
Sep 20, 2016 3:56:43 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Shutdown complete
[main] ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW …
```
> Support for webdriver.ie.driver system property

- serenity-core/src/main/java/net/thucydides/core/requirements/classpath/NarrativeText.java
- serenity-core/src/test/groovy/net/thucydides/core/requirements/WhenLoadingNarrativeDescriptionFromADirectory.groovy
- serenity-core/src/test/groovy/net/thucydides/core/requirements/WhenLoadingRequirementsFromAPackageStructure.groovy
- serenity-core/src/test/java/net/thucydides/core/requirements/WhenCountingRequirementsInOutcomes.java
There are some issues caused  build/test  failure under windows system.
1. path conversion and computation.
2. new line wrap
3. regex pattern, etc.
18 tests failed, left one failure.
````
net.thucydides.core.requirements.WhenAssociatingATestOutcomeWithARequirementByPackage > Should find the requirement for a given tag FAILED
Condition not satisfied:
requirement.get().narrative.renderedText.contains "I want to grow potatoes"
|           |     |         |            |
|           |     |         ""           false
|           |     net.thucydides.core.requirements.model.CustomFieldValue@65826fe1[name=Narrative,text=,renderedText=<null>]
|           Requirement{name='Grow potatoes', type='capability' parent = 'null', cardNumber='null', narrative …
```
> partial work for fixing windows build failure.

- serenity-core/src/main/java/net/serenitybdd/core/pages/DropdownDeselector.java
- serenity-core/src/main/java/net/serenitybdd/core/pages/WebElementFacade.java
- serenity-core/src/main/java/net/serenitybdd/core/pages/WebElementFacadeImpl.java
- serenity-core/src/main/java/net/thucydides/core/webdriver/stubs/WebElementFacadeStub.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/DeselectFromOptions.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/SelectFromOptions.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/deselectactions/DeselectAllOptions.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/deselectactions/DeselectByIndexFromTarget.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/deselectactions/DeselectByValueFromTarget.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/deselectactions/DeselectByVisibleTextFromTarget.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/selectactions/SelectByIndexFromBy.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/selectactions/SelectByIndexFromElement.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/selectactions/SelectByValueFromBy.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/selectactions/SelectByValueFromElement.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/selectactions/SelectByVisibleTextFromBy.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/selectactions/SelectByVisibleTextFromElement.java
- serenity-screenplay-webdriver/src/test/java/net/serenitybdd/screenplay/webtests/WhenDanaSelectsHerContactPreferences.java
- serenity-screenplay-webdriver/src/test/java/net/serenitybdd/screenplay/webtests/pages/ProfilePage.java
- serenity-screenplay-webdriver/src/test/java/net/serenitybdd/screenplay/webtests/questions/ContactPreferences.java
- serenity-screenplay-webdriver/src/test/java/net/serenitybdd/screenplay/webtests/tasks/DeselectAll.java
- serenity-screenplay-webdriver/src/test/java/net/serenitybdd/screenplay/webtests/tasks/DeselectContactPreference.java
- serenity-screenplay-webdriver/src/test/java/net/serenitybdd/screenplay/webtests/tasks/SelectContactPreference.java
- serenity-screenplay-webdriver/src/test/resources/sample-web-site/profile.html
**Issue #551: added support for deselecting options**
There didn't seem to be a screenplay way to deselect options either in screenplay or core modules, so this PR adds to `WebElementFacade`:
- `deselectAll()` - often needed when we want to start off input with a 'clean slate' on a muli-select element.
- `deselectByVisibleText()`, `deselectByValue()`, `deselectByIndex()` - mirrors of the methods implemented for `Select`.
The following deselect actions were created in the screenplay webdriver module:
- `DeselectByIndexFromTarget`
- `DeselectByValueFromTarget`
- `DeselectByVisibleTextFromTarget`
The above were only created for Target as my assumption is that we should not be encouraging people to be working directly with `By` or `Element` and it ends up conflating the api anyway.
**Note**: …
> Issue #551: added support for deselecting options

- serenity-core/src/main/java/net/serenitybdd/core/webdriver/driverproviders/InternetExplorerDriverProvider.java
#612: Apply user properties to recommended default Internet Explorer capabilities, not the other way around
- Prior to this PR, the user properties containing driver capabilities e.g. `serenity.driver.capabilities=unexpectedAlertBehavior:ignore;ie.ensureCleanSession:true;logLevel:INFO;logFile:target/ie.log` were used as a basis for capability creation, but then they were overidden with sensible defaults in InternetExplorerDriverProvider. This seems back to front as the user properties should always be last in the order of resolution, so the order has now been changed to reflect that.
> #612: Apply user properties to recommended Internet Explorer defaults

- serenity-rest-assured/src/main/java/net/serenitybdd/rest/decorators/request/RequestSpecificationDecorated.java
- serenity-rest-assured/src/test/groovy/net/serenitybdd/rest/WhenRunningRestTestsThroughJUnitWithoutSerenity.groovy
- serenity-rest-assured/src/test/groovy/net/serenitybdd/rest/WhenRunningRestTestsWithoutSerenity.groovy
It allows to use SerenityRest without a proper setup of Serenity, particularly without any BaseStepListener registered.
The above makes possible to share test code between Serenity tests and plain JUnit tests. No need to implement the same in SerenityRest and in Rest Assured.
It only tries to register rest calls if a BaseStepListener is registered (which is the expected state while running SerenityRest code with Serenity runners). It logs an info message otherwise (expected behaviour while running SerenityRest code from non-Serenity runners, e.g. plain JUnit).
Run any SerenityRest code, e.g. rest().get("http://github.com"), from a plain JUnit test.
A NullPointerException (with "No BaseStepListener has been registered" message) is not thrown when running tests which uses SerenityRest from …
> Ability to use SerenityRest from a plain JUnit runner, issue #695

- serenity-core/src/main/java/net/serenitybdd/core/webdriver/driverproviders/FirefoxDriverProvider.java
This PR is a fix for #751 
When setting a webdriver.gecko.driver environment variable with a valid geckodriver file path, MarionetteDriver should be instantiated.
If the webdriver.gecko.driver is not set, the current behavior is in effect: if geckodriver executable is in path MarionetteDriver is instantiated, else FirefoxDriver is instantiated.
> Issue #751: fix: geckodriver is used from WEBDRIVER_GECKO_DRIVER environment variable

- serenity-core/src/main/java/net/thucydides/core/ThucydidesSystemProperty.java
Thucydides constants have been tagged as deprecated.  Comments have been moved to Serenity equivalents.
Relates to #784
> Created Serenity equivalents for all non Deprecated Thucydides methods

- serenity-core/src/main/java/net/thucydides/core/webdriver/capabilities/AddCustomCapabilities.java
This is a fix for: #781
We call this method with: ["browserstack."](https://github.com/bebef1987/serenity-core/blob/077dbc9174f64c78f32e759598305058f7098d8c/serenity-core/src/main/java/net/thucydides/core/webdriver/capabilities/BrowserStackRemoteDriverCapabilities.java#L47) and then add a extra '.' 
In the split we will have something like: remove browserstack.. from browserstack.build
This method will have no effect.
And add
> Reove extra'.' for capability getPreparedPropertyKey

- serenity-core/src/main/java/net/thucydides/core/reflection/MethodFinder.java
- serenity-core/src/main/java/net/thucydides/core/steps/AnnotatedStepDescription.java
- serenity-core/src/test/java/net/thucydides/core/steps/WhenDescribingStepsUsingAnnotations.java
This is a fix for  #713
We need to check if we have multiple methods with the same name and use the one with the correct number of arguments.
> Step multiple implementation annotation

- serenity-core/src/main/java/net/thucydides/core/webdriver/capabilities/RemoteTestName.java
This is a fix for #846 Test Name is not sent to Browserstack
Some of the methods in the stacktrace will return exception when calling `callingClass.getMethod(elt.getMethodName());` but when we reach the targeted method will return a valdi result.
Ignoring the exceptions will generate the desired result
> Fix #846 Test Name is not sent to Browserstack

- serenity-core/src/main/java/net/thucydides/core/util/PropertiesFileLocalPreferences.java
- serenity-core/src/main/java/net/thucydides/core/util/PropertiesUtil.java
- serenity-core/src/test/groovy/net/serenitybdd/core/WhenSettingSerenitySystemProperties.groovy
- serenity-core/src/test/java/net/thucydides/core/util/WhenProcessingProperties.java
Environment variables can be references using ${AN_ENVIRONMENT_VARIABLE} and System Properties using ${system.property.example}.
> feat: Expand references to environment variables and system propertiesin serenity.conf & serenity.properties.

- serenity-core/src/main/java/net/thucydides/core/reports/AcceptanceTestFullReporter.java
- serenity-core/src/main/java/net/thucydides/core/reports/ReportService.java
Hi!
We are testing with Cucumber features. And we want to generate reports like JUnit, with the tag 
> "\<testsuites name=...>"
with the attribute "name", the name of the feature, and where every scenario is a testsuite tag, and every step a testCase... 
But this can not be done with the current AcceptanceTestReporter as it sends a **TestOutcome** but not the **TestOutcomes**.
This new AcceptanceTestFullReporter (maybe you can find a better name!) can execute 
"_generateReportsFor(final TestOutcomes testOutcomes)_" (as done in **JUnitXMLOutcomeReporter**...)
> add method with TestOutcomes, in a listener to generate reports

- serenity-appium/README.md
- serenity-appium/pom.xml
- serenity-appium/serenity.properties
- serenity-appium/src/test/java/integration/WordPressAppTest.java
- fixed script as per latest changes in framework related to appium driver handling in saucelabs
- https://github.com/serenity-bdd/serenity-core/commit/6f815a2153217e61c800c6efbe2d75c41586ba97
- "When you use saucelabs or browserstack, Serenity will now check if you are also using appium. If you are, it will use an IOSDriver or AndroidDriver. Otherwise, it will use a RemoteDriver."
@wakaleo Please review
> refactoring as per appium driver related changes

- serenity-core/src/main/java/net/thucydides/core/model/featuretags/StoryFileStrategy.java
- serenity-core/src/main/java/net/thucydides/core/reflection/ClassFinder.java
Minor refactoring - replace a few invocations of `System.out.println` with SLF4J API invocations 
For now class `net.thucydides.core.model.featuretags.StoryFileStrategy` produces 2 log lines like next while running Serenity-JBehave story file `stories/dir1/dir2/SomeTest.story`:
```
Story name for stories/dir1/dir2/SomeTest.story => TestTag{name='My Tag Name', type='story'}
Story name for stories/dir1/dir2/SomeTest.story => TestTag{name='My Tag Name', type='story'}
```
When set of stories is running, it becomes a bit annoying, because no way to turn it off. With this PR it be easily disabled from local logger framework configuration, e.g. via log4j2:
```
#src/main/resources/log4j2-test.properties
logger.mylog.name=net.thucydides.core.model.featuretags
logger.mylog.level=INFO
```
setting …
> refactor: replace System.out.println with logger API call

- serenity-core/src/main/java/net/serenitybdd/core/annotations/findby/di/ClasspathCustomFindByAnnotationProviderService.java
- serenity-core/src/main/java/net/serenitybdd/core/annotations/findby/di/CustomFindByAnnotationProviderService.java
- serenity-core/src/main/java/net/serenitybdd/core/annotations/findby/di/CustomFindByAnnotationService.java
- serenity-core/src/main/java/net/serenitybdd/core/annotations/locators/SmartAnnotations.java
- serenity-core/src/main/java/net/thucydides/core/annotations/locators/SmartFieldDecorator.java
- serenity-core/src/main/java/net/thucydides/core/guice/ThucydidesModule.java
- serenity-core/src/test/groovy/net/serenitybdd/core/annotations/locators/FindByCustom.groovy
- serenity-core/src/test/groovy/net/serenitybdd/core/annotations/locators/WhenUsingTheSmartAnnotations.groovy
- serenity-core/src/test/java/net/serenitybdd/core/annotations/findby/di/ClasspathCustomFindByAnnotationProviderServiceTest.groovy
- serenity-core/src/test/java/net/serenitybdd/core/annotations/findby/di/CustomSampleFindByAnnotationService.java
- serenity-core/src/test/resources/META-INF/services/net.serenitybdd.core.annotations.findby.di.CustomFindByAnnotationService
Hi!
We are testing react components using https://www.npmjs.com/package/retractor. To facilitate the implementation of the tests we want to use a custom annotation. Like in this question: https://stackoverflow.com/questions/46039246/custom-annotation-creation-initialization-issue-with-serenity-framework
With this PR this is possible adding an implementation of the interface CustomFindByAnnotationService
> add custom findBy

- serenity-core/src/main/java/net/thucydides/core/model/TitleBuilder.java
- serenity-core/src/test/groovy/net/thucydides/core/model/WhenBuildingATitle.groovy
With this fix HTML reports display the correct font-awesome icon for the internet explorer (i.e. when the context was set to `ie`)
Perform some webtest with `-Dcontext=ie` and examine the HTML report. The icon for the internet explorer should be displayed.
Also a unit test for the `TitleBuilder` class has been added.
https://github.com/serenity-bdd/serenity-core/issues/1057
> Fixed internet explorer icon for context 'ie' for #1057

- gradle.properties
@wakaleo Please review this PR, in this I've updated appium java client to latest version to debug https://github.com/serenity-bdd/serenity-core/issues/1053
I've run command `gradle clean test integrationTests`. Please refer to attached screen shot.
There are 7 browser related failures, which existed earlier as well.
> updated appium java client version

- serenity-core/src/main/java/net/thucydides/core/reports/junit/JUnitXMLConverter.java
Hi,
I'm facing the same issue as the closed https://github.com/serenity-bdd/serenity-core/issues/843 issue.
The following deps are used:
compile group: 'net.serenity-bdd', name: 'serenity-core', version: '1.8.21'
compile group: 'net.serenity-bdd', name: 'serenity-junit', version: '1.8.21'
compile group: 'net.serenity-bdd', name: 'serenity-rest-assured', version: '1.8.21'
compile group: 'net.serenity-bdd', name: 'serenity-jbehave', version: '1.35.0'
Error message:
`Wrong timestamp format was generated: for example: "2018-01-09T16:38:20.646+02:00[Europe/Helsinki]"`
This is causing the report generation to break.
After some digging I traced this issue back to commit e655282e446bdb3bfbd78aca346577c15f2b8983
In the `JUnitXMLConverter` a `ZonedDateTime.toSting()` method is used on the starttime …
> Fixed JUNIT XML generation issue.

- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/targets/IFrameSwitcher.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/targets/TargetResolver.java
- attempt to avoid `Unable to locate frame` exception as seen in the integration tests on master. Note that this is only likely to work if the DOM is in a state of transition to the correct content within the duration of the expected condition. This may not address the problem in  [jenkins integration build #251](http://34.248.197.198:8080/blue/rest/organizations/jenkins/pipelines/serenity-core/pipelines/integration-tests/runs/251/log/?start=0) where the browser page source on the failing tests seems fixed as follows:
```
<?xml version="1.0" encoding="UTF-8"?>
<html>
<head/>
<body/>
</html>
```
> FIX: #1172: switch iframe using expected condition

- serenity-core/src/main/java/net/thucydides/core/reports/junit/JUnitXMLConverter.java
Corrected date format to use day of month. Currently its using day-of-year which causes to fail from today.
> Fixing  JUnitXMLConverter uses wrong timestamp format #1195

- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/targets/IFrame.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/targets/IFrameSwitcher.java
- serenity-screenplay-webdriver/src/test/java/net/serenitybdd/screenplay/webtests/integration/WhenDanaBrowsesTheWeb.java
- In order support switching between elements that are in differently nested iframes, a switch to default content is needed before switching to iframe(s), to avoid element not found exception.
> #1217 bug: iframe switching

- serenity-core/src/main/java/net/thucydides/core/steps/StepAnnotations.java
- serenity-model/src/main/java/net/thucydides/core/ThucydidesSystemProperty.java
Made it possible to define maximum step nesting level to facilitate projects with huge amounts of step classes, also increased the default maximum step nesting from 16 to 32.
If actual infinite recursion happens it may take a tiny bit longer to detect it.
#1288
> fix: added SERENITY_MAXIMUM_STEP_NESTING_DEPTH property for #1288

- serenity-report-resources/src/main/resources/freemarker/libraries/favicon.ftl
This PR fixes the Favicon not being shown when serenity reports (index.html) are generated.
Serenity reports should show a Favicon when opened in browser. Currently the favicon file itself is outdated. It is the old favicon which does not match the below logo but the favicon will be visible after this fix. To match the favicon with logo, We need to update the resource files in `serenity-report-resources/src/main/resources/report-resources`
Go to `serenity-spring`
From terminal run `./gradlew clean test`
This should generate a target folder. Go to `target/site/serenity` and open any file (which are individual screenshots) with .html
The page should open and Favicon can be seen on browser tab.
https://github.com/serenity-bdd/serenity-core/issues/890
> Fix report (index.html) Favicon for #890

- serenity-screenplay/src/main/java/net/serenitybdd/screenplay/Actor.java
- serenity-screenplay/src/test/groovy/net/serenitybdd/screenplay/WhenActorsHaveAbilities.groovy
Per this question in the Users Group: https://groups.google.com/d/msg/thucydides-users/zhuJAmHe2Iw/p09T97eQAQAJ
Allow subclassing of Abilities e.g. BrowseTheWeb
> fix: Treat subclasses of an Ability as the superclass Ability

- serenity-core/src/main/java/net/serenitybdd/core/di/WebDriverInjectors.java
- serenity-gradle-plugin/src/main/groovy/net/serenitybdd/plugins/gradle/SerenityPlugin.groovy
- serenity-model/src/main/java/net/thucydides/core/guice/Injectors.java
Reverts serenity-bdd/serenity-core#1399 - causes an error "Could not set unknown property 'reportDirectory' for task ':checkOutcomes' of type org.gradle.api.DefaultTask"
> Revert "Gradle plugin class SerenityPlugin is not thread-safe"

- serenity-core/src/main/java/net/serenitybdd/core/webdriver/driverproviders/ChromeDriverCapabilities.java
Update chromeOptions to set w3c=true as per https://wiki.saucelabs.com/display/DOCS/Selenium+W3C+Capabilities+Support+-+Beta#SeleniumW3CCapabilitiesSupport-Beta-chromeOptions 
Able to use both Google Chrome and Firefox on Saucelabs
Run tests against Saucelabs Firefox and Chrome.  Be sure to specify the seleniumVersion corresponding to that in gradle.properties (not Saucelabs default)
N/A
N/A
#1468
N/A
Regarding all the changes listed in https://wiki.saucelabs.com/display/DOCS/Selenium+W3C+Capabilities+Support+-+Beta
* version -> browserVersion: This is not yet used in Selenium (https://github.com/SeleniumHQ/selenium/search?l=Java&q=BROWSER_VERSION) as of 2018-11-30.  The current corresponding line of code in Serenity is https://github.com/serenity-bdd/serenity-core/blob/master/serenity-cor …
> Address #1486 - Saucelabs/Chrome

- serenity-core/src/main/java/net/thucydides/core/webdriver/capabilities/SaucelabsRemoteDriverCapabilities.java
- serenity-core/src/main/java/net/thucydides/core/webdriver/capabilities/SetAppropriateSaucelabsPlatformVersion.java
- serenity-model/src/main/java/net/serenitybdd/core/buildinfo/BuildInfoProvider.java
- serenity-model/src/main/java/net/thucydides/core/ThucydidesSystemProperty.java
Summary of this PR
Update version to browserVersion as per https://wiki.saucelabs.com/display/DOCS/Selenium+W3C+Capabilities+Support+-+Beta#SeleniumW3CCapabilitiesSupport-Beta-version
Intended effect
Able to use the intended browser version
How should this be manually tested?
Run tests against Saucelabs Firefox and Chrome. Be sure to specify the seleniumVersion corresponding to that in gradle.properties (not Saucelabs default)
Side effects
N/A
Documentation
N/A
Relevant tickets
#1468-this is a bit of an addendum to PR #1470.  Notes there about version->browserVersion were incorrect.
Screenshots (if appropriate)
N/A
> Fix 1468: update capability passed to sauce from version to browserVersion

- serenity-core/src/main/java/net/thucydides/core/webdriver/ElementLocatorFactorySelector.java
- serenity-core/src/main/java/net/thucydides/core/webdriver/appium/AppiumConfiguration.java
- serenity-core/src/test/groovy/net/thucydides/core/webdriver/appium/WhenConfiguringAnAppiumDriver.groovy
If there's a platformName specified in the desiredCapabilities, use that. Otherwise, use the context for the platformName. If that doesn't work use the property appium.platformName.
> #1528 allow the platformName to be specified in more ways

- serenity-core/src/main/java/net/thucydides/core/webdriver/ThucydidesConfigurationException.java
- serenity-core/src/test/groovy/net/thucydides/core/webdriver/appium/WhenConfiguringAnAppiumDriver.groovy
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/targets/ByTarget.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/targets/LocatesCrossPlatform.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/targets/TargetBuilder.java
- serenity-screenplay-webdriver/src/test/groovy/net/serenitybdd/screenplay/targets/WhenDefiningTargets.groovy
Add the ability to define one locator for Android and another for iOS. If one is defined, the other also must be. The correct locator will be returned based on the `platformName` set on the driver for the `Actor` resolving the `Target`.
Usage example:
`Target.the("Cross Platform By Target").locatedForAndroid(MobileBy.id("android_element_id")).locatedForIOS(MobileBy.id("iOS_element_id"))`
> feat: support unique locators for iOS and Android (fixes #1531)

- serenity-core/src/main/java/net/thucydides/core/webdriver/appium/AppiumConfiguration.java
- serenity-core/src/test/groovy/net/thucydides/core/webdriver/appium/WhenConfiguringAnAppiumDriver.groovy
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/targets/ByTarget.java
Also checks that platformName exists in the capabilities to avoid NullPointerException
>  Use platformName instead of platform when deciding the MobilePlatform

- serenity-core/src/main/java/net/serenitybdd/core/pages/WebElementFacade.java
- serenity-core/src/main/java/net/serenitybdd/core/pages/WebElementFacadeImpl.java
Deprecated old withTimeoutOf(int, TimeUnit) method and replaced with withTimeoutOf(Duration) for WebElementFacade to bring it in line with the PageObject implementation.
fixes #1564
> Make WebElementFacade withTimeoutOf method signature consistent with PageObject

- serenity-report-resources/src/main/resources/report-resources/css/core.css
Format change in oder to prevent project banner to bleed into the breadcrumbs
> Fix for Issue: How to use a long project name without overlapping the breadcrumbs line? #1597

- serenity-model/src/main/java/net/thucydides/core/reports/html/ResultCounts.java
- serenity-report-resources/src/main/resources/freemarker/home.ftl
- serenity-report-resources/src/main/resources/freemarker/outcomes-with-result.ftl
- serenity-report-resources/src/main/resources/freemarker/requirements.ftl
even when all the tests are passing, the link to “unsuccessful” test results remains active, but leads to a non-existent page
> report bugfix: disable link to "Unsuccesful" tests when all tests are passing

- serenity-report-resources/src/main/resources/report-resources/css/core.css
* Maintain whitespace formatting of the message
* Font change to monospace, black and slightly smaller
An example of the changes:
> Improve report error message readability

- serenity-junit/src/main/java/net/serenitybdd/junit/runners/DataDrivenAnnotations.java
- serenity-junit/src/main/java/net/serenitybdd/junit/runners/SerenityParameterizedRunner.java
- serenity-junit/src/test/java/net/serenitybdd/junit/runners/integration/WhenRunningADataDrivenTestScenario.java
Fix using test tags for parameterized JUnit test classes containing multiple test methods.
> fix: Test tags for parameterized JUnit tests: #1378 and #1261

- serenity-screenplay/src/main/java/net/serenitybdd/screenplay/Actor.java
- serenity-screenplay/src/main/java/net/serenitybdd/screenplay/HasTeardown.java
- serenity-screenplay/src/main/java/net/serenitybdd/screenplay/actors/Cast.java
- serenity-screenplay/src/test/groovy/net/serenitybdd/screenplay/actors/WhenRecruitingACast.groovy
Abilities represent a particular API to the SUT. In some cases there will be resources specific to that API which will need to be cleaned up upon completion of the test. This change allows that to be defined for each Ability, so that regardless of what Cast/Actors/Abilities are being used in a test, only `Onstage.drawTheCurtain()` needs to be called and all of the tear down will be performed.
> feat: the teardown for an Ability will be called from Onstage.drawTheCurtain()

- serenity-screenplay/src/main/java/net/serenitybdd/screenplay/EventualConsequence.java
- serenity-screenplay/src/test/java/net/serenitybdd/screenplay/ThisTakesTooLong.java
- serenity-screenplay/src/test/java/net/serenitybdd/screenplay/shopping/DanaGoesShoppingSample.java
- serenity-screenplay/src/test/java/net/serenitybdd/screenplay/shopping/questions/NextPersonToBeServed.java
- serenity-screenplay/src/test/java/net/serenitybdd/screenplay/shopping/tasks/Checkout.java
- serenity-screenplay/src/test/java/net/serenitybdd/screenplay/shopping/tasks/JoinTheCheckoutQueue.java
changed orComplainWith and other chained methods to use a different constructor, timeout and isSilent should now persist
fixes #1677 
I am not sure how to test the isSilent though..
> fix: orComplainWith did override the timeout of EventualConsequence

- serenity-report-resources/src/main/resources/freemarker/home.ftl
It looks like these exclamation marks were added erroneously in 9d7f7a77
> fix: Remove exclamation marks from the Page Title

- serenity-report-resources/src/main/resources/freemarker/default.ftl
Updates the HTML report to enable nested steps to be collapsible.
The HTML report should allow every level of nested steps to control their own ability to collapse/expand. 
I was unable to find any serenity demo/example projects which utilise multiple levels of nested steps.
All nested steps will be affected due to the removal of the `level == 1` condition.
#1004 
**Before**
**After**
> #1004: Update HTML report to implement expansion/collapse of nested steps

- serenity-core/src/main/java/net/thucydides/core/annotations/locators/WaitForWebElementCollection.java
The original intent of this pull request is to work around StaleElementReferenceException that sometimes  occurs when visiting list of WebElement annotated with FindBy.
When page is updated, the WebElements in the collection appear stale. When Serenity PageObject is trying to revisit this collection, directly calling WebElement::isDisplayed() method throws StaleElementReferenceException. To handle this, for `Paranoid` strategy it is handled by using ElementIsUsable::forElement() that handles generic WebDriverException. On the contrary, the default `Pessimistic` strategy does not handle exception at all.
DISCLAIMER: I haven't had a chance to run CI on this change - please suggest documentation on it
> Handle any WebDriverException when evaluating usability of webelements collection for default strategy.

- serenity-model/src/main/java/net/thucydides/core/ThucydidesSystemProperty.java
- serenity-model/src/main/java/net/thucydides/core/reports/html/TagFilter.java
- serenity-model/src/main/java/net/thucydides/core/util/TagInflector.java
- serenity-model/src/test/java/net/thucydides/core/util/TagInflectorTest.java
- serenity-report-resources/src/main/resources/freemarker/components/tag-list.ftl
- serenity-report-resources/src/main/resources/freemarker/default.ftl
- serenity-report-resources/src/main/resources/freemarker/home.ftl
- serenity-report-resources/src/main/resources/freemarker/outcomes-with-result.ftl
- serenity-reports/src/main/java/net/thucydides/core/reports/html/FreemarkerContext.java
- serenity-reports/src/main/java/net/thucydides/core/reports/html/HtmlAcceptanceTestReporter.java
Proposal for #1764 
Improve tags readability in HTML report.
Using installed changes on serenity-cucumber test framework, do next:
* Add tags like `@mytag:value_under_test`, `@mytag:AnotherTag` to Cucumber scenario;
* define Serenity property `report.raw.tag.list=mytag`;
* execute tests and aggregate report;
* check report - `mytag` tags should be `value_under_test` and `AnotherTag` (not `Value Under Test` and `Another Tag` respectively)
If property enabled, next will be affected:
* tags in tag dashboard on the bottom of index.html page;
* Outcome-with-results page title;
* list of tags on detailed results page;
However, next won't be affected:
* tag in `Functional Coverage Overview` table;
* tag in page breadcrumbs.
Javadoc for `ThucydidesSystemProperty.REPORT_RAW_TAG_LIST` added.
#1764 …
> feat: allow keep tags unformatted via 'report.raw.tag.list' property

- serenity-model/src/main/java/net/thucydides/core/util/PropertiesFileLocalPreferences.java
- attempt to load Typesafe config from classpath if no properties conf resolved from any of the following
1) -Dproperties=<value>
2) src/test/resources/serenity.conf
4) src/main/resources/serenity.conf
> #1775 - Environment configuration not being read since 2.0.63

- serenity-gradle-plugin/src/main/groovy/net/serenitybdd/plugins/gradle/SerenityPlugin.groovy
Refactor some code to prevent a StackOverflowError for older gradle versions
I tried writing tests for this in the repository but ran into a lot of issues.
Will add a link to the commit where I tried to test this so maybe someone will be able to help me.
the `checkOutcomes` task should now succeed on older gradle versions
Apply the new version of the serenity-gradle-plugin on a trial project
N/A
N/A
#1797
N/A
> Prevent StackOverflowError during checkOutcomes task with older gradle versions. fixes #1797

- serenity-core/src/main/java/net/thucydides/core/webdriver/appium/AppiumConfiguration.java
- serenity-core/src/test/groovy/net/thucydides/core/webdriver/appium/WhenConfiguringAnAppiumDriver.groovy
- serenity-model/src/main/java/net/thucydides/core/ThucydidesSystemProperty.java
Filter desired capabilities for initiating Appium session - by default, only [supported by w3c](https://www.w3.org/TR/webdriver/#capabilities) and [Appium](http://appium.io/docs/en/writing-running-appium/caps/) are kept, so things like _appium.hub_ or _loggingPref_ won't be included in desired capabilities. 
However, it is possible that interfaces in [java-cllient](https://github.com/appium/java-client) do not contain all of the supported values - so new property `appium.additional.caps` was added to ThucydidesSystemProperty enum to handle such cases. 
For example, now **appium.unlockKey** is not present in AndroidMobileCapabilityType right now, even though it is supported by Appium. Such properties should be prefixed with **appium:** to comply w3c pattern. In order to do that …
> #1812 Filter desired capabilities

- serenity-core/src/main/java/net/thucydides/core/webdriver/appium/AppiumConfiguration.java
- serenity-core/src/test/groovy/net/thucydides/core/webdriver/appium/WhenConfiguringAnAppiumDriver.groovy
- serenity-model/src/main/java/net/thucydides/core/ThucydidesSystemProperty.java
As result of changes introduced by [pull request](https://github.com/serenity-bdd/serenity-core/pull/1824), it is not possible anymore to put properties, that are not supported by w3c/appium, in desired capabilities (adding them to _appium.additional.capabilities_ doesn't help much, because as result in desired capabilities they are prefixed with _appium:_ and it is not expected by external services).
New property - _appium.process.desired.capabilities_ introduced. By default it is disabled, so everything that is prefixed with _appium:_ will be added to desired capabilities without any changes (fix for https://github.com/serenity-bdd/serenity-core/issues/1831). 
If this property enabled, then filtering + processing will be applied to provided properties while creating desired …
> #1831 Disable processing desired capabilities for Appium

- serenity-model/src/main/java/net/serenitybdd/core/environment/EnvironmentSpecificConfiguration.java
- serenity-model/src/test/groovy/net/serenitybdd/core/environment/WhenDefiningBaseUrlsForDifferentEnvironments.groovy
Fixes the situation that no properties are found with environments specified in serenity.conf but no environment named
If environments are configured but no environment is named, null was returned for any requested property. With this fix, normal properties are used.
An automated test describing the configuration was added.
None - regression tests passed.
Usage outlined in the automated test as well as in the corresponding issue.
#1839
> #1839 EnvironmentStrategy ENVIRONMENT_CONFIGURED_BUT_NOT_NAMED considered

- serenity-core/src/main/java/net/serenitybdd/core/annotations/locators/SmartAnnotations.java
- serenity-core/src/main/java/net/thucydides/core/annotations/locators/SmartFieldDecorator.java
Added iOSClassChain and iOSNSPredicate in valid locator strategies.
Added iOSXCUITFindBy and some other valid annotations in Legal annotations to find list of elements. 
iOS Appium test should be fixed if they are using Class chain and ios predicate as locators. 
An automated appium test for iOS using class chain and ios predicate string locator strategies to find list of elements or just an element can test this. 
None - regression tests passed.
Check the corresponding issue created. 
#1846
> Fix : iOS locator strategies need to be added in WebElementFacade FindBy strategies #1846

- .gitattributes
- build.gradle
- serenity-core/src/main/java/net/thucydides/core/annotations/TestCaseAnnotations.java
- serenity-core/src/main/java/net/thucydides/core/annotations/UsePersistantStepLibraries.java
- serenity-core/src/main/java/net/thucydides/core/steps/StepInterceptor.java
- serenity-core/src/main/java/net/thucydides/core/util/ExtendedTemporaryFolder.java
- serenity-core/src/main/java/net/thucydides/core/webdriver/capabilities/BrowserStackRemoteDriverCapabilities.java
- serenity-core/src/main/java/net/thucydides/core/webdriver/capabilities/RemoteTestName.java
- serenity-junit/build.gradle
- serenity-junit/src/test/java/net/thucydides/core/util/WhenRunningWithoutJUnit5.java
- serenity-model/build.gradle
- serenity-model/src/main/java/net/thucydides/core/reflection/ClassFinder.java
- serenity-model/src/main/java/net/thucydides/core/requirements/PackageAnnotationBasedTagProvider.java
- serenity-model/src/main/java/net/thucydides/core/requirements/PackageRequirementsTagProvider.java
- serenity-model/src/main/java/net/thucydides/core/requirements/SerenityTestCaseFinder.java
- serenity-model/src/main/java/net/thucydides/core/requirements/annotations/ClassInfoAnnotations.java
- serenity-model/src/main/java/net/thucydides/core/tags/TagScanner.java
- serenity-model/src/main/java/net/thucydides/core/util/JUnitAdapter.java
- serenity-model/src/test/java/net/thucydides/core/util/JUnitAdapterUnitTest.java
The runtime dependency on JUnit (4) is removed by providing an adapter that is able to use either a Junit 4 or Junit 5 strategy, or both after another, or none at all, based on which JUnit version is available at runtime.
The behavior of Serenity should not change if used as before (i.e. with a not-excluded transitive dependency on JUnit 4). But it should now be able to exclude the transitive dependency on Junit 4 at runtime without causing runtime errors. And adding a dependency to JUnit 5 would handle JUnit 5 tests similar to how JUnit 4 tests are handled.
All tests based on JUnit 4 should work as before. The regression test suites already go a long way to ensure this.
There is a new compile-time-only dependency on Junit 5 that will affect only developers working on (and not just with) …
> #1858 Decoupled serenity-model and serenity-core from JUnit (4)

- serenity-model/src/main/java/net/thucydides/core/model/failures/FailureAnalysisConfiguration.java
*Brief summary*
When throwing exception: net.serenitybdd.core.SkipStepException during test then test result is PENDING instead of SKIPPED. This code fixes wrong behaviour.
*How I did it changes*
Instead of adding SkipStepException to DEFAULT_PENDING_TYPES, I add it to DEFAULT_SKIPPED_TYPES. Moreover, I've refactored variable name in skippedTypes() function to more precise one.
*Additional changes*
> Skipped Scenario Fix

- serenity-core/src/main/java/net/serenitybdd/core/webdriver/driverproviders/ChromeDriverCapabilities.java
Apologies, looks like the values come in without the prefix. This sorts it out
> #1821 Removed "chrome_experimental_options" prefix

- serenity-report-resources/src/main/resources/freemarker/home.ftl
- serenity-report-resources/src/main/resources/report-resources/css/core.css
- serenity-reports/src/main/java/net/thucydides/core/reports/html/FreemarkerContext.java
- serenity-reports/src/test/java/net/thucydides/core/reports/integration/WhenGeneratingAnAggregateHtmlReportSet.java
Similar to email report, users can use the same configuration as email report to make custom fields displayed in the home page of aggregate report. This can help with #1454.
> feat: Custom fields in home page of aggregate report

- serenity-report-resources/src/main/resources/freemarker/components/requirements-list.ftl
There was a random `style="padding:0px;` in `requirements-list-ftl` under the serenity-report-resources module. That made the progress bars that contained percentages to go up in the parent table cell. This PR removes it.  
Vertical alignment of the progress bars to the center of the cell.
1. Use any of the demo projects to generate a report;
2. Navigate to the Requirements tab > Test Results;
3. Check the progress bar(s). It should be aligned to the vertical center.
None.
N/A.
#1879 
BEFORE:
AFTER:
> fix for #1879

- serenity-report-resources/src/main/resources/report-resources/css/core.css
Serenity reports are limited to ~1024px in width. This PR removes this limit.
The report fills the page, making mor space for feature/stories names in results tables, for instance
1. Use any of the demo projects to generate a report;
2. Report should be generated without width constraints.
None.
N/A
#1887 
CURRENT:  
PROPOSAL:
> proposal for #1887

- serenity-report-resources/src/main/resources/report-resources/css/core.css
Reverts serenity-bdd/serenity-core#1888
Styling doesn't work well for result tables:
> Revert "proposal for #1887"

- serenity-report-resources/src/main/resources/freemarker/default.ftl
- serenity-report-resources/src/main/resources/report-resources/css/core.css
**Summary of this PR**
Serenity reports are limited to ~1024px in width. This PR removes this limit.
Fixed results tables pointed out in #1896 
Also tested with extra long data tables (see screens).
**Intended effect**
The report fills the page, making mor space for feature/stories names in results tables, for instance
**How should this be manually tested?**
1. Use any of the demo projects to generate a report;
2. Report should be generated without width constraints.
**Side effects**
None.
**Documentation**
N/A
**Relevant tickets**
#1887 
**Screenshots (if appropriate)**
MAIN REQUIREMENT:
HOME PAGE:
RESULTS TABLES:
FEATURE SPECS:
EXAMPLE WITH SCREENSHOTS:
> proposal for #1887 (2nd attempt)

- serenity-core/src/main/java/net/thucydides/core/webdriver/appium/AppiumConfiguration.java
- serenity-core/src/test/groovy/net/thucydides/core/webdriver/appium/WhenConfiguringAnAppiumDriver.groovy
- serenity-model/src/main/java/net/thucydides/core/model/TestOutcome.java
When an specific environment is used serenity was sending all appium properties which cause for example that if an IOS environment was specified then appium also receive properties for android if they exists.
Also added a fix to include context in TestOutcome constructors and clone methods.
> Fix appium specific environment bug.

- serenity-core/src/test/java/net/thucydides/core/steps/WhenDescribingStepsUsingAnnotations.java
- serenity-model/src/main/java/net/thucydides/core/steps/AnnotatedStepDescription.java
- serenity-model/src/main/java/net/thucydides/core/steps/ExecutedStepDescription.java
Now it should be possible to refer to the property or method of the provided parameter based on the additional instructions in @Step annotation -- more detailed description provided in this [issue](https://github.com/serenity-bdd/serenity-core/issues/1922)
> feat: Process complex step parameters

- serenity-core/src/main/java/net/thucydides/core/steps/BaseStepListener.java
- serenity-junit/src/main/java/net/serenitybdd/junit/runners/SerenityRunner.java
Minor fix of tag value, applied to passed junit tests after rerun.
Number of test retries should be reported correctly.
* Introduce some flaky serenity-junit test;
* run test with property `test.retry.count=10`;
* Make sure that flaky test pass not in 1st try, but in some next try;
* Open generated page and check number of retries, reported in `unstable test` tag
Documentation for `TEST_RETRY_COUNT` system property already exists.
#1997 
Please check related issue.
> fix: issue 1997 - report correct number of junit retries

- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/targets/ByTarget.java
When the called method is used with a ByTarget, the name of the target is not updated due to a typo that doesn't set the new name to the target.
> Fix a typo bug in ByTarget

- serenity-model/src/main/java/net/thucydides/core/requirements/model/cucumber/CucumberParser.java
- serenity-model/src/test/groovy/net/thucydides/core/requirements/model/cucumber/WhenReferencingScenariosInAFeatureNarrative.groovy
- serenity-model/src/test/resources/serenity-cucumber/features/maintain_my_todo_list/filtering_todos.feature
In the current version, running serenity:aggregate with -Dcucumber.filter.tags only works if the tags are at the feature level. If the filtered tags are at scenario, scenario outlines, or examples, the aggregate report would have blank requirements, capabilities, and features pages because the Requirement object only contains feature TestTag.
I only fixed it simply by including all the tags in the feature files. Seems like it has always been like this. Let me know if this is by design.
Please delete options that are not relevant.
I added a unit test. Also built locally and did e2e test.
> fix: requirements not displayed on aggregate report when running with cucumber filter tags

- serenity-model/src/main/java/net/thucydides/core/requirements/model/cucumber/CucumberParser.java
- serenity-model/src/test/groovy/net/thucydides/core/requirements/model/cucumber/WhenReferencingScenariosInAFeatureNarrative.groovy
- serenity-model/src/test/resources/serenity-cucumber/features/maintain_my_todo_list/filtering_todos.feature
Reverts serenity-bdd/serenity-core#2102 as it breaks #2053
> Revert "fix: requirements not displayed on aggregate report when running with cucumber filter tags"

- serenity-screenplay/src/main/java/net/serenitybdd/screenplay/InstrumentedTask.java
I used `./gradlew install` to install the snapshot. So I was able to prove that my fix does **not** work. :(
Once the code gets into `isInstrumented(Performable task)`, at that point `task` is already null. So in my "fix" `task.getClass()` throws another NPE.
I am not able to find a better solution.
> 'task' is already null by the time code gets here.

- serenity-core/src/main/java/net/serenitybdd/core/webdriver/driverproviders/ChromeDriverCapabilities.java
- serenity-core/src/main/java/net/serenitybdd/core/webdriver/driverproviders/DriverCapabilities.java
- serenity-core/src/main/java/net/serenitybdd/core/webdriver/driverproviders/EdgeDriverProvider.java
- serenity-core/src/main/java/net/serenitybdd/core/webdriver/driverproviders/FirefoxDriverCapabilities.java
- serenity-core/src/main/java/net/thucydides/core/webdriver/CapabilityEnhancer.java
As of Selenium 4.0 the DesiredCapabilities browser factory methods are deprecated.
This commit only removes the calls from the `main` source.
I have not yet checked the amount of work to refactor the tests.
One thing that draw my attention was the fact Edge doesn't have a `DriverCapabilitiesProvider`, but as I'm not aware of its need I left it the way it is, please let me know if it should be addressed as well!
More context: https://github.com/SeleniumHQ/selenium/commit/e615772723158a74003bc8ea57f87880b8cccb21
> Stop using deprecated DesiredCapabilities in main

- serenity-core/src/main/java/net/thucydides/core/model/screenshots/ScreenshotPermission.java
- serenity-model/src/test/groovy/net/thucydides/core/model/screenshots/WhenDecidingWhetherToTakeScreenshots.groovy
Now the ScreenshotPermission class will first try to see if there is an Screenshot annotation over the current test step method, if present then it will use that configuration otherwise will use the current behavior .
FIX #1982
@wakaleo let me know if u have comments.
> :bug: FIX screenshot configuration on step methods

- serenity-rest-assured/src/main/java/net/serenitybdd/rest/decorators/request/RequestSpecificationDecorated.java
- serenity-rest-assured/src/test/groovy/net/serenitybdd/rest/WhenRecordGetRequestsWithSerenityRest.groovy
If there are multiple custom filters in the request, then serenity report is missing the REST query.
```
given()
.baseUri("http://…")
.filters(Arrays.asList(new FirstFilter(), new SecondFilter()))
```
Support for a single filter is part of #1175, and this PR adds support for multiple filters
> feat: Accept multiple custom filters in request

- serenity-core/src/main/java/net/serenitybdd/core/pages/WebElementFacadeImpl.java
`net.serenitybdd.core.pages.WebElementFacadeImpl#waitUntilNotVisible` contains a guard to return if the element is not present: `withTimeoutOf(Duration.ofMillis(0)).isVisible()`. But although the timeout is set to `0` this method will not return immediately like `WebElementFacadeImpl#isCurrentlyVisible`. 
The difference here is that `SmartAjaxElementLocator#findElement` will take a moment (depending on the configured implicit timeout) because it will use `SmartAjaxElementLocator#ajaxFindElement` (while `isCurrentlyVisible` will use `SmartAjaxElementLocator#findElementImmediately`).
```
findElement:113, SmartAjaxElementLocator (net.thucydides.core.annotations.locators)
resolveForDriver:30, WebElementResolverByElementLocator (net.serenitybdd.core.pages)
getResolvedELement:235, …
```
> fix: WebElementFacade#waitUntilNotVisible returns immediately if the element is currently not visible

- gradle.properties
- serenity-core/build.gradle
- serenity-model/build.gradle
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/SerenityRest.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/decorators/ResponseSpecificationDecorated.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/decorators/request/RequestSpecificationBodyConfigurations.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/decorators/request/RequestSpecificationConfigurable.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/decorators/request/RequestSpecificationDecorated.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/decorators/request/RequestSpecificationLoggable.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/decorators/request/RequestSpecificationParametersConfigurations.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/decorators/request/RequestSpecificationSecurityConfigurations.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/stubs/RequestSpecificationStub.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/stubs/ResponseSpecificationStub.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/stubs/ResponseStub.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/stubs/ValidatableResponseStub.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/utils/RestReportingHelper.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/utils/RestResponseRecordingHelper.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/utils/RestSpecificationFactory.java
- serenity-rest-assured/src/test/groovy/net/serenitybdd/rest/WhenExecutingWrappedMethods.groovy
- serenity-rest-assured/src/test/groovy/net/serenitybdd/rest/WhenRunningRestTestsThroughSerenity.groovy
- serenity-rest-assured/src/test/groovy/net/serenitybdd/rest/configuring/WhenConfiguringDefaultParameters.groovy
- serenity-rest-assured/src/test/groovy/net/serenitybdd/rest/requests/WhenExecutingPostRequest.groovy
- serenity-smoketests/build.gradle
- serenity-test-utils/build.gradle
Relates to #2145
Continuation of https://github.com/serenity-bdd/serenity-core/pull/2147
Upgrade rest-assured to 4.2.0.
I know that the newest version is 4.3.1, but it requires more work to do, so let's do it step by step.
> rest-assured 3.3.0 -> 4.2.0

- gradle.properties
webdrivermanager version 4.2.0 had issues with Beta version of browsers; see https://github.com/bonigarcia/webdrivermanager/issues/548 for discussion.
> use latest and fixed version

- build.gradle
- gradle.properties
- serenity-asciidoc/build.gradle
- serenity-browsermob-plugin/build.gradle
- serenity-core/build.gradle
- serenity-ensure/build.gradle
- serenity-json-summary-report/build.gradle
- serenity-junit/build.gradle
- serenity-model/build.gradle
- serenity-reports-configuration/build.gradle
- serenity-reports/build.gradle
- serenity-rest-assured/build.gradle
- serenity-screenplay/build.gradle
- serenity-single-page-report/build.gradle
- serenity-stats/build.gradle
- Upgrade to rest-assured 4.3.1
- Upgrade Groovy to 3.0.5 (rest-assured since 4.3.0 use Groovy 3.x)
- Upgrade Spock to Groovy 3.x version (right now `2.0-M3-groovy-3.0` version available)
> Upgrade to rest-assured 4.3.1

- serenity-model/src/main/java/net/thucydides/core/requirements/model/cucumber/CucumberParser.java
- serenity-model/src/test/groovy/net/thucydides/core/requirements/model/cucumber/WhenLoadingFeaturesInOtherLanguage.groovy
- serenity-model/src/test/groovy/net/thucydides/core/requirements/model/cucumber/WhenLoadingIncorrectFeatureFiles.groovy
- serenity-model/src/test/resources/features/maintain_my_todo_list/feature_en_otro_idioma.feature
FIX #2146
@wakaleo, @cliviu I change the current implementation of the cucumber parser to use the FeatureParser provided by cucumber instead of rely on Gherkin implementation, because current CucumberParser was unable to handle Features in other languages different of english that are not encoding as UTF-8.
I added a test, that verifies this, also I test this in my project and now the Features are not duplicated anymore, let me know any comment.
> :bug: Updates CucumberParser to handle features in other languages or  encodings

- serenity-core/src/main/java/net/serenitybdd/core/pages/WebElementFacadeImpl.java
- serenity-core/src/test/java/net/thucydides/core/pages/integration/UsingTheWebElementFacade.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/ClickOnClickable.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/ClickOnElement.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/ClickOnTarget.java
- serenity-screenplay/src/main/java/net/serenitybdd/screenplay/Actor.java
- serenity-screenplay/src/main/java/net/serenitybdd/screenplay/Forget.java
- serenity-screenplay/src/main/java/net/serenitybdd/screenplay/questions/TheMemory.java
- serenity-screenplay/src/test/groovy/net/serenitybdd/screenplay/WhenActorsForgetStuff.groovy
Actors are now able to forget things, this is something really easy to made in Kotlin but in Java is more verbose, so I added the method to forget in the Actor class.
:bug: FIX #2243  this fixes the report things for ClickInteraction, also the ClickOnElement class now uses the CLICK_STRATEGY provided.
:bug: FIX #2168
> :sparkles: Add forget option to actors

- serenity-core/src/main/java/net/thucydides/core/webdriver/ElementLocatorFactorySelector.java
Fixes an inconsistency in `ElementLocatorFactorySelector` where it's AppiumConfiguration uses a different EnvironmentVariables than other usages.
ElementLocatorFactorySelector will assign the target platform consistent with the passed configuration.
- Start with a configuration that does not contain `appium.platformName` (previously this would later be read by Injectors)
- make a copy of the configuration and update with a valid platformName
- pass updated configuration to ElementLocatorFactorySelector
- call elementLocatorFactorySelector.getLocatorFor(MobileDriver)
**Expected:**
AppiumConfiguration.getTargetPlatform() does not throw a ThucydidesConfigurationException stating the platformName is not defined
#2281
> Ensure appiumConfiguration is consistent when choosing an ElementLocatorFactory (#2281)

- serenity-crossbrowsertesting/build.gradle
- serenity-crossbrowsertesting/src/main/java/net/serenitybdd/crossbrowsertesting/AfterACrossBrowserTestingScenario.java
- serenity-crossbrowsertesting/src/main/java/net/serenitybdd/crossbrowsertesting/BeforeACrossBrowserTestingScenario.java
- serenity-crossbrowsertesting/src/main/java/net/serenitybdd/crossbrowsertesting/CrossBrowserTestingTestSession.java
- serenity-crossbrowsertesting/src/test/java/net/serenitybdd/crossbrowsertesting/WhenAddingCrossBrowserTestingCapabilities.java
- settings.gradle
Integrates SerenityBDD with [CrossBrowserTesting](https://crossbrowsertesting.com/) (A service similar to BrowserStack/Saucelabs)
- adds the ability to configure drivers for cbt.
- marks the test outcome in cbt
- attaches the cbt test session link to the serenity report
- Sign up for a free trial of CBT
- in your serenity.conf place the following:
```
webdriver.remote.driver = chrome
webdriver.remote.url = "http://<user>:<key>@hub.crossbrowsertesting.com:80/wd/hub"
crossbrowsertesting {
browserName = chrome
browserVersion = Latest
platformName = "Windows 10"
record_video = true
}
```
- run your test
- after the test is completed, the session is marked as pass/fail in cbt
- open the serenity report, view the test results. A link to the test session is attached to the results (camera icon) …
> Smartbear crossbrowsertesting support

- serenity-core/src/test/java/net/thucydides/core/annotations/WhenReadingTestAndStepAnnotations.java
- serenity-model/src/main/java/net/thucydides/core/annotations/TestAnnotations.java
* use MethodFinder to lookup method in test class  (e.g. to find non public Junit5 @Test method with @Title and @WithTag)
* alternative could be to move the decision which methods to consider to the `JUnitStrategy`
> Consider annotations on non-public test methods (TestAnnotations)

- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/CheckCheckbox.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/CheckCheckboxOfElement.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/CheckCheckboxOfTarget.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/UncheckCheckbox.java
Adds support for Checking/Unchecking checkboxes in screenplay
Users now have access to `CheckCheckbox.of(target)` or `UncheckCheckbox.of(target)` that ensures the checkbox is in the intended state
#2319
> CheckCheckbox interaction

- serenity-model/src/main/java/net/thucydides/core/model/TestOutcome.java
:bug: FIX a bug that causes current context to be overridden when calling `getEnvironmentVariables` method in TestOutcome
FIX #2129
possible FIX #2172
> :bug: FIX a bug that causes current context to be overriden

- serenity-model/src/main/java/net/thucydides/core/reports/AsciiColors.java
fix for https://github.com/serenity-bdd/serenity-maven-plugin/issues/77
> default SERENITY_CONSOLE_COLORS to false, as per documentation

- serenity-browserstack/src/main/java/net/serenitybdd/browserstack/AfterABrowserStackScenario.java
- serenity-browserstack/src/main/java/net/serenitybdd/browserstack/BrowserStackTestSession.java
Adds some additional getters to retrieve properties from the Browserstack API
Users will have the ability to query the bstack api for all [session detail properties](https://www.browserstack.com/docs/automate/api-reference/selenium/session#get-session-details)
In my case I needed a way to reliably get os/browser version. Browserstack doesn't allow minor os versions to be assigned by device capabilities (for iOS) and by default will always get the latest stable browser
- Requires a Browserstack Automate account and at least 1 saved session
```
public class WhenGettingBrowserStackSessionInfo {
BrowserStackTestSession session;
@Before
public void setup() {
session = new BrowserStackTestSession("BSTACK USER", "BSTACK KEY", "BSTACK SESSION ID");
}
@Test
public void canGetName() { …
```
> Additional Browserstack session getters

- serenity-core/src/main/java/net/serenitybdd/core/webdriver/servicepools/DriverServiceExecutable.java
Currently, the configuredPath method only looks at environment variables, so it ignores the downloaded webdriver, now it will try to check also at system property.
FIX #2409
> :bug: Search for webdriver in System properties. 

- serenity-model/src/main/java/net/thucydides/core/reflection/MethodFinder.java
- serenity-model/src/main/java/net/thucydides/core/steps/AnnotatedStepDescription.java
Hi,
this PR should address 2 issues which we faced recently
a) while resolving step name, sometime we got not consistent results (`NoSuchElementException` was thrown at attempt to get value from `annotatedStepName` variable). The cause of this exception is that in `stepName()` method `isPresent()` is called not for variable, but for the result of another invocation of `getAnnotatedStepName()`). So it is possible that `annotatedStepName` is empty, but check won't catch it
b) find method not only by parameters count, but try to find by types first of all. it is possible to have several overloaded methods with the same name and parameters count, but different types, so it would be nice to find the right one. previous logic was preserved, so if for some reason we can't find method with …
> Find methods by param types

- gradle.properties
- pom.xml
Serenity BDD reports issues with illegal reflective access, caused by Guice (see google/guice#1133):
```
➜ npx serenity-bdd run                                                                                                                                                                                                                                                                                   20:02  [397ccd3]
Spawning: /usr/lib/jvm/java-11-openjdk-amd64/bin/java -Dserenity.compress.filenames=true -DLOG_LEVEL=warn -Dlogback.configurationFile=/home/rod/serenity-js-cucumber-protractor-template/node_modules/@serenity-js/serenity-bdd/resources/logback.config.xml -jar node_modules/@serenity-js/serenity-bdd/cache/serenity-cli-2.3.31.jar --destination target/site/serenity --features …
```
> Upgraded Guice to 5.0.1

- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/EnterValueIntoElement.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/EnterValueIntoTarget.java
In https://github.com/serenity-bdd/serenity-core/commit/d92aa0cfb46886c98cc734ae8feb3b96626cadd0 Enter actions were changed from type to sendActions which caused failures of tests. Instead of setting a value, value was getting appended to an existing one.
> Revert changes related to entering a value into element

- serenity-core/src/main/java/net/thucydides/core/webdriver/appium/AppiumConfiguration.java
appium does support opening an already installed app using its appPackage and appActivity properties.
As such, its not mandatory to have app property.  Even providing appPackage and appActivity could be fine. So, adding a check.
> Update AppiumConfiguration.java to relax check on app property

- serenity-core/src/main/java/net/thucydides/core/webdriver/CapabilitySet.java
- serenity-core/src/test/groovy/net/thucydides/core/webdriver/WhenConfiguringExtraWebdriverCapabilities.groovy
The problem was that nested JSON objects in capabilities configuration weren't correctly parsed. Instead of adding the whole JSON object as a value, first half of it was set as part of key.
The issue wasn't found previously because corresponding test wasn't written.
Additionally, adding a comment to the unclear logic in CapabilityToken.
> Configure webdriver capabilities using maps/JSON objects

- serenity-core/src/main/java/net/thucydides/core/steps/StepAnnotations.java
- serenity-core/src/main/java/net/thucydides/core/steps/construction/StepsClassResolver.java
- serenity-core/src/test/java/net/thucydides/core/steps/WhenResolvingStepsObjects.java
- serenity-core/src/test/resources/META-INF/services/net.thucydides.core.steps.construction.StepsClassResolver
I'd like to propose new feature to be added to Serenity - an option to resolve actual step object implementation at runtime. The idea behind that is to have several implementation of the same step object and provide possibility to pick up needed one based on some conditions or preferences. It might be the same action from business logic standpoint, but with some difference in the interactions with application under test. So we can extend parent class, override some method and then use this inherited class in some circumstances. 
It is completely up to the implementation how real class for the steps is resolved.
So now it should be possible to define step object as:
- interface
- abstract class
- regular class (and then define inherited class that should be used instead of parent)
In all …
> Resolve step objects dynamically

- serenity-screenplay-rest/src/main/java/net/serenitybdd/screenplay/rest/questions/RestQuestionBuilder.java
- serenity-screenplay-rest/src/test/java/net/serenitybdd/screenplay/rest/examples/SampleWhenRetrievingUserDetails.java
Now, `withQueryParameters(String param1, Object value1, Object... otherParams)` and `withPathParameters(String param1, Object value1, Object... otherParams)` get wrong value. For example
```
.withQueryParameters("page", page, "count", 1)
```
will produce wrong result
```
https://reqres.in/api/users?page=2&count=count
```
After the fix, the result will be
```
https://reqres.in/api/users?page=2&count=1
```
> fix: Fix withQueryParameters() and withPathParameters() get wrong value

- serenity-core/src/main/java/net/serenitybdd/core/webdriver/driverproviders/AddLoggingPreferences.java
- serenity-core/src/main/java/net/serenitybdd/core/webdriver/driverproviders/EdgeDriverCapabilities.java
Edge args like "ignore-certificate-errors" weren't picked up properly because of blank logging and pref properties.
This was resulting in failing test because of certificate errors.
Fix typo in "ms:edgeChrominum".
> Add logging and Edge prefs option only when not empty

- serenity-core/src/main/java/net/thucydides/core/steps/CleanupMethodLocator.java
- serenity-core/src/main/java/net/thucydides/core/steps/StepEventBus.java
- serenity-core/src/main/java/net/thucydides/core/steps/StepInterceptor.java
- serenity-screenplay/src/main/java/net/serenitybdd/screenplay/Actor.java
Currently when an action or screenplay task is executed on the `@after` method, if the task was a Rest interaction then an NPE will be thrown if a previous step in the test had failed, this was due to the way how serenity invokes methods through byte-buddy, this PR, adds a logic to avoid DryRunExecution when a method is called inside a clean method (After hooks in Cucumber), with this fix when a method is invoked inside an After hook then a normal execution will be used.
With the previous fix, another thing appears, on Screenplay when a Task or Consequence is evaluated, at the end any previous exception will be rethrown which causes that if in an After hook you have multiple actions only the first one is executed, to avoid this, now the `endperfomance` logic will check if currently, we …
> :ambulance: FIX an error when executing actions on After methods

- serenity-junit5/src/main/java/net/serenitybdd/junit5/PendingTestException.java
- serenity-junit5/src/main/java/net/serenitybdd/junit5/SkippedTestException.java
replaced junit4 dependency with junit5 compatible version of org.opentest4j to solve  #2686
> serenity-junit5: replace junti4 with org.opentest4j pendants

- serenity-browserstack/src/main/java/net/serenitybdd/browserstack/BrowserStackTestSession.java
Fixes a minor issue. Retrieving null session properties should no longer throw an exception.
- Attempt to retrieve a session property that is null (e.g. The browser version of a mobile device).
- This should no longer throw an exception
> fix: BrowserStack session properties not parsed correctly if null

- serenity-core/src/main/java/net/serenitybdd/core/photography/WebDriverScreenShooter.java
- serenity-core/src/main/java/net/thucydides/core/webdriver/SerenityWebdriverManager.java
- serenity-core/src/main/java/net/thucydides/core/webdriver/WebdriverInstances.java
1. When a new driver is going to be added to the map of the Webdriver instance, Serenity will check using a more smart approach, first, it will check if both drivers are equals, if not then it will see if the mapped driver is a Facade and the new driver is not, in that case, the check will happen against the proxied driver, finally, if previous checks fail it will assume the new driver is a facade and mapped one isn't.
2. If the driver is Appiumdriver assume the driver name as appium, currently chrome was used.
3. If an exception happens taking a screenshot, log a warn, it doesn't matter the exception type. 
FIX #2757
> :bug: Fix Appium errors taking screenshot

- serenity-core/src/main/java/net/serenitybdd/core/pages/PageUrls.java
Fixes issue #2753.
When calling 
`page.open(withParameters(...))`
webdriver.base.url won`t be processed twice.
> fix: PageObject#open() with parameters adds base url twice to page DefaultUrl

- build.gradle
- serenity-ant-task/build.gradle
- serenity-asciidoc/build.gradle
- serenity-assertions/build.gradle
- serenity-browsermob-plugin/build.gradle
- serenity-browserstack/build.gradle
- serenity-core/build.gradle
- serenity-crossbrowsertesting/build.gradle
- serenity-ensure/build.gradle
- serenity-json-summary-report/build.gradle
- serenity-junit/build.gradle
- serenity-junit5/build.gradle
- serenity-model/build.gradle
- serenity-navigator-report/build.gradle
- serenity-reports-configuration/build.gradle
- serenity-reports/build.gradle
- serenity-rest-assured/build.gradle
- serenity-sample-alternative-resources/build.gradle
- serenity-saucelabs/build.gradle
- serenity-screenplay-rest/build.gradle
- serenity-screenplay-webdriver/build.gradle
- serenity-screenplay/build.gradle
- serenity-shutterbug/build.gradle
- serenity-shutterbug1x/build.gradle
- serenity-single-page-report/build.gradle
- serenity-smoketests/build.gradle
- serenity-spring/build.gradle
- serenity-stats/build.gradle
- serenity-zalenium/build.gradle
The gradle build for serenity-junit was using `compile` and `testCompile` configurations that leak dependencies to external projects. This commit fixes the leak
> fix: (gradle) serenity-junit fix dependencies leak (fixes #2815)

- serenity-model/src/main/java/net/thucydides/core/guice/Injectors.java
- serenity-reports/src/main/java/net/thucydides/core/reports/html/HtmlAggregateStoryReporter.java
- serenity-reports/src/main/java/net/thucydides/core/reports/html/HtmlReporter.java
The current guice module configuration (https://github.com/serenity-bdd/serenity-core/blob/cfecbd98a95e875d7540c0b8123d3e33363d4ed7/serenity-model/src/main/java/net/thucydides/core/guice/ThucydidesModule.java#L68-L72) declares https://github.com/serenity-bdd/serenity-core/blob/008f81a8e37d87a4b3b6711e252b4ffd897f2e34/serenity-model/src/main/java/net/thucydides/core/util/EnvironmentVariables.java as Singletone.
When using gradle in its default configuration as daemon and applying the serenity-gradle-plugin, this Singleton is created on first run and cannot be modified later. Any configuration change requires restarting the gradle daemon. What is worse is that there is no indication of this happening.
This PR allows for providing a different guice configuration. The serenity-gradle-plugin …
> Make bindings customizable

- serenity-browsermob-plugin/pom.xml
to reflect its purpose. Original name was wrong probably due to copy/paste.
> style: rename maven module serenity-browsermob-plugin

- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/matchers/statematchers/IsNotCurrentlyEnabledMatcher.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/matchers/statematchers/IsNotCurrentlyVisibleMatcher.java
This PR fixes the wrong error messages in `IsNotCurrentlyEnabledMatcher.java` and `IsNotCurrentlyVisibleMatcher.java`.
Before this change the error message for a failed `IsNotCurrentlyVisible()` call is for instance:
```
Expected: an element that is not currently visible
but: the element identified by [[RemoteWebDriver] -> css selector: .some-css-class] [] was not currently visible
```
After the change the error message is for instance:
```
Expected: an element that is not currently visible
but: the element identified by [[RemoteWebDriver] -> css selector: .some-css-class] [] was visible
```
> fix: change is no currently matcher error messages

- gradle.properties
- serenity-core/build.gradle
- serenity-junit5/src/main/java/net/serenitybdd/junit5/SerenityTestExecutionListener.java
- serenity-junit5/src/test/java/net/serenitybdd/junit5/WhenDetectingASerenityJUnit5TestClass.java
- serenity-model/build.gradle
- serenity-reports/build.gradle
Fixes #3117: tests that were using multiple @ExtendWith- or the @Extension-annotation were not recognized are serenity-tests.
Updated gradle-dependencies to match maven-versions if I encountered compile errors (at first I didn't know which of both tools I should use).
#3117
> Fix #3117 recognize serenity-tests with multiple @ExtendWith and fix gradle-build

- serenity-core/src/main/java/net/serenitybdd/core/pages/ListOfWebElementFacades.java
Given there is more than 1 element returned by the locator so gets resolved to ListOfWebElementFacades
And I want to filter the resulting list based on the predicate (isDisplayed for instance)
And I want to benefit from fallback functionality handling StaleElementReferenceException
When I filter ListOfWebElementFacades
I should get the resulting list matching the condition provided
> Added filter to ListOfWebElementFacades

- build.gradle
- gradle.properties
- pom.xml
- serenity-assertions/pom.xml
- serenity-bitbar/pom.xml
- serenity-browserstack/pom.xml
- serenity-cli/pom.xml
- serenity-core/pom.xml
- serenity-crossbrowsertesting/pom.xml
- serenity-cucumber/pom.xml
- serenity-jira-plugin/pom.xml
- serenity-jira-requirements-provider/pom.xml
- serenity-json-summary-report/pom.xml
- serenity-junit/pom.xml
- serenity-junit5/build.gradle
- serenity-junit5/pom.xml
- serenity-model/pom.xml
- serenity-navigator-report/pom.xml
- serenity-reports-configuration/pom.xml
- serenity-reports/pom.xml
- serenity-rest-assured/pom.xml
- serenity-saucelabs/pom.xml
- serenity-screenplay-playwright/pom.xml
- serenity-shutterbug/pom.xml
- serenity-single-page-report/pom.xml
- serenity-smoketests/pom.xml
- serenity-stats/pom.xml
@wakaleo I struggle to update serenity version >3.8.1 due to junit error
Junit5 dependency version was not the same on all modules, so to fix it, I used the bom junit5
The same done for cucumber.
Note: for gradle, I just see the requirements in https://docs.gradle.org/current/userguide/java_testing.html#using_junit5, but did not test it
Note2: After this fix, this allows me to identify again issues with 2 versions of groovy in rest-assured module (3.0.18 + 4.0.13)
> Fix junit5 dependency version and review Cucumber dependencies

- serenity-model/src/main/java/net/thucydides/model/domain/TestResult.java
- serenity-model/src/test/java/net/thucydides/model/domain/TestResultTest.java
Fix for incorrect final test result in `SerenityTestExecutionListener` when JUnit test throws exception.
net.serenitybdd.junit5.SerenityTestExecutionListener#testFinished returns FAILED result for JUnit tests failed with exception.
use tests from #3298.
Unit test is added.
Not sure.
#3298
> Fix for incorrect final test result when JUnit test throws exception (ticket #3298)

- serenity-browserstack/src/main/java/net/serenitybdd/plugins/browserstack/BrowserStackConfiguration.java
Automatically Session Name marking broken in `serenity-browserstack-plugin` due to
```
WARNING: Support for Legacy Capabilities is deprecated; You are sending the following invalid capabilities: ["bstack:options"]; Please update to W3C Syntax: https://www.selenium.dev/blog/2022/legacy-protocol-support/
```
> Bug fix: W3c non-compliant capability "bstack:options"

- serenity-core/src/main/java/net/serenitybdd/core/reports/AddReportContentEvent.java
- serenity-core/src/main/java/net/serenitybdd/core/reports/ReportDataSaver.java
Refactor the code to add files to test steps to follow the same methods and way as adding text. This fixes the adding of files to corresponding test steps in the report as that is currently not working.
When using the method `Serenity.recordReportData().withTitle(String title).fromFile(Path path));` the file will be connected in the report to the corresponding step.
To test this use the method described above in your code and verify the existance of the button to download the file at the corresponding step in the generated report.
-
-
https://github.com/serenity-bdd/serenity-cucumber-starter/issues/132
> #132 Fix adding files to corresponding test steps in the report

- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/selectactions/SelectByValueFromBy.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/selectactions/SelectByValueFromElement.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/selectactions/SelectByValueFromTarget.java
This fixes the issue that the wrong parameter ("#value") is used in the Serenity report instead of the correct one ("#values").
> fix: step message of SelectByValue performables

- serenity-model/src/main/java/net/thucydides/model/domain/TestStep.java
For the cases when TestStep has nested steps (=children), `getChildResults(`) will be invoked in order to calculate the final result.  It will be done for every node, that has children itself. However, with the current implementation amount of those calls is enormous. 
Let's imagine following case, when there is 3 level of nested steps:
```
TestStep parentStep = new TestStep("Test Step: Level 0");
int level = 3;
TestStep currentStep = parentStep;
for (int i = 1; i <= level; i++) {
TestStep childStep = new TestStep("Test Step: Level "+ i);
currentStep.addChildStep(childStep);
currentStep = childStep;
}
```
With current implementation call to `getResult()` method would produce the output like (debug output was added for demonstration purposes):
```
Get result for step on level: 0
Get child …
```
> fix: TestStep - optimize method to obtain result

- serenity-core/src/main/java/net/thucydides/core/steps/StepInterceptor.java
- serenity-core/src/test/java/net/thucydides/core/steps/WhenRecordingStepExecutionResults.java
- serenity-core/src/test/java/net/thucydides/core/steps/samples/FlatScenarioSteps.java
This PR fixes the condition introduced in [this](https://github.com/serenity-bdd/serenity-core/commit/f6224ed203963689c41880b33a5946c3c39db535) commit. In our case, if the soft assertions are enabled, step results should be reported accordingly without checking if one of the previous steps failed. However, with this change, if there was a failing step (e.g. with exception) during test execution, listener wasn't notified properly - so that new group was created for every failing step (except the first one, which was processed correctly).
Unit test added to cover this scenario
> Notify step failure in StepInterceptor if soft assertion enabled

- serenity-junit5/src/main/java/net/serenitybdd/junit5/ParameterizedTestsOutcomeAggregator.java
- serenity-junit5/src/test/java/net/serenitybdd/junit5/samples/integration/displayName/JUnit5CustomDisplayNameExample.java
Updated the baseMethodName so that we can effectively handle display names, display name generators, and methods without JUnit custom display names
> Updated the baseMethodName so that we can effectively handle display names, display name generators, and methods without JUnit custom display names

- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/matchers/statematchers/isClickableMatcher.java
This fixes the clickable mismatch message from
```
Expected: an element that is clickable
but: no matching element found by [[RemoteWebDriver] -> css selector: button[value='submit']] was not clicked
```
to
```
Expected: an element that is clickable
but: no matching element found by [[RemoteWebDriver] -> css selector: button[value='submit']] was not clickable
```
> fix: clickable mismatch message

- serenity-screenplay-rest/src/main/java/net/serenitybdd/screenplay/rest/interactions/Ensure.java
Added CanBeSilent interface to the Ensure class and created a new method silentlyThat that sets isSilent to true.
The existing method signature and behaviour is unchanged.
Ensure can now be used in a test and not show on the report.
Create a test such as 
```
import net.serenitybdd.screenplay.rest.interactions.Ensure;
...
bob.attemptsTo(
Get.resource("/xyz")
Ensure.silentlyThat(response->response.statusCode(200))
Ensure.that("gets a successful response", response->response.statusCode(200))
);
```
Only the second check will be displayed on the report.
There are no side effects. The existing functions signature and behaviour is unchanged.
I could not find any documentation for this version of Ensure.
> feat: Allow screenplay rest ensure interaction to be silent.

- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/questions/page/TheWebPage.java
By adding `source()` to `TheWebPage.java` the actor is able to validate source code of the page, e.g.
```
actor.should( seeThat( TheWebPage.source(), containsString( "Test" ) ) );
```
> feat: add source() to get the source of a page

- serenity-cucumber/src/main/java/io/cucumber/core/plugin/SerenityReporterParallel.java
up to serenity 4.0.50 we used the SerenityReporterPlugin to extend it and provide tight integration betwene Tiger and Serenity. Now with the plugin being deprecated and the parallel plugin taking over we need protected access to a few methods.
> extending SerentyParallelReport plugin for integration with Tiger

- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/ui/PageElement.java
due to the missing . character in the xpath, it was not possible to locate nested elements by tag, as the elements were being searched for in document root rather than current node. The applied fix resolves this issue.
> fix: small locator fix for by tag in page element

- serenity-core/src/main/java/net/thucydides/core/steps/StepEventBus.java
instead, use computeIfAbsent() to instantiate StepEventBus only when needed
> perf: avoid creating unused StepEventBuses

- serenity-rest-assured/src/main/java/net/serenitybdd/rest/RestStepListener.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/utils/RestReportingHelper.java
since it no longer does anything
> refactor: deprecate RestStepListener (#3540)

- serenity-core/src/main/java/net/serenitybdd/core/webdriver/driverproviders/AppiumDriverProvider.java
- serenity-core/src/main/java/net/thucydides/core/webdriver/MobilePlatform.java
fixes https://github.com/serenity-bdd/serenity-core/issues/3493
> Add Appium Windows platform

- serenity-model/src/main/java/net/thucydides/model/domain/Story.java
Edge case scenario converting file name to uri which misses the scheme leading to failure
> Fix for #3258 - Handle path related issues in Windows

- serenity-core/src/main/java/net/serenitybdd/core/Serenity.java
It seems recently the functionality for throwsExceptionImmediately has changed, a new thread local was created but it seems it was not used
> fix: throw exception immediately

- serenity-report-resources/src/main/resources/freemarker/home.ftl
This fixes a problem in generated reports, when the user provided text fields contain HTML
The HTML in the fields is escaped. This PR builds on the work done in https://github.com/serenity-bdd/serenity-core/pull/3523
> Ensure HTML is properly escaped for all user-provided text properties

- serenity-maven-plugin/src/main/java/net/serenitybdd/maven/plugins/SerenityAggregatorMojo.java
This pull request addresses Issue #3590 by including a logger.info statement that outputs the URI of the full report.
Users can now see the URI to the full Serenity report in the console output when running acceptance tests with Maven. This enhancement improves user experience by making it easier to locate the full report.
- Clone the Serenity Cucumber Starter project from [here](https://github.com/serenity-bdd/serenity-cucumber-starter).
- Update the serenity version `<version>4.2.10-SNAPSHOT</version>`
- Run the acceptance tests using Maven: mvn clean verify.
- Verify that the console output includes a log message with the URI to the full Serenity report
No known side effects. The change is scoped to the logger.info output and only triggered when serenity.generateFullReport is undefined …
> #3590 log uri to full report when running aggregate goal

- serenity-core/src/main/java/net/thucydides/core/steps/BaseStepListener.java
- serenity-core/src/main/java/net/thucydides/core/steps/StepEventBus.java
- serenity-core/src/main/java/net/thucydides/core/steps/StepInterceptor.java
- serenity-cucumber/src/main/java/io/cucumber/core/plugin/ScenarioContextParallel.java
- serenity-cucumber/src/main/java/net/serenitybdd/cucumber/events/StepFinishedWithResultEvent.java
If a step is calling a behaviour that calls a sub-step which fails in an error and the outer step is catching the error and does not throw, the test report produces a wrong indentation for the subsequent steps. 
This PR fixes that in such a way that a step failure does not automatically close the step but each step is alway claused by a step finished event. Thus, the subsequent event parsing only pops a step from the step stack when encountering a finished event and during a step, any number of (caught but reported) failures can occur without breaking the report.
This probably also fixes the issue https://github.com/serenity-bdd/serenity-core/issues/3489
> Deal consistently with steps throwing exception which is caught by enclosing step.

- serenity-screenplay-playwright/src/main/java/net/serenitybdd/screenplay/playwright/abilities/BrowseTheWebWithPlaywright.java
Fix: Replaced colon (":") with hyphen ("-") in the test outcome name used for generating the trace file name. This update ensures that generated file names are valid across all operating systems.
> Fix invalid characters in trace file name

- serenity-screenplay-playwright/pom.xml
- serenity-screenplay-playwright/src/test/java/net/serenitybdd/screenplay/playwright/abilities/WhenAnActorWantsToUsePlaywright.java
Update Playwright to 1.52.0
Allows using the "chromium" channel.(new headless mode).
> Playwright update

- serenity-report-resources/src/main/resources/report-resources/css/core.css
Tags are difficult to read at failed scenarios in the report - see the "Before" screenshot:
Before:
After:
Used test scenarios: https://github.com/Rudolf-AT/serenity-report-tag-contrast
> feat: improve contrast of tag at failed test in the report.

- serenity-core/src/test/groovy/net/thucydides/core/requirements/WhenGeneratingRequirementsReportData.groovy
generate requirements once, all use the same, pass vars to filesystemprovider
clear cache
add somehow needed requirement types property
> fix test interference
