- core/src/main/java/net/thucydides/core/pages/components/FileToUpload.java
Changed creation of file path (if file in classpath)
> Fix problem with uploading file on Windows. 

- serenity-core/src/main/java/net/thucydides/core/webdriver/WebDriverFactory.java
> Fix for setting up the remote webdriver capability: webdriver.remote.browser.version

- serenity-core/src/main/java/net/thucydides/core/steps/StepFactory.java
Discussed in https://github.com/serenity-bdd/serenity-core/issues/106
> Fix inject Pages in super class

- serenity-core/src/main/java/net/thucydides/core/steps/BaseStepListener.java
Hi , please see https://github.com/serenity-bdd/serenity-core/issues/37. The test program given by the user has the expected output after the change
> see https://github.com/serenity-bdd/serenity-core/issues/37

- serenity-core/src/main/java/net/thucydides/core/reports/html/Formatter.java
- serenity-report-resources/src/main/resources/freemarker/default.ftl
proposed fix for 
https://github.com/serenity-bdd/serenity-core/issues/125
This makes my report generation work, not sure whether it is in line with this projects coding guidelines or design intentions
> fix: prevent null pointers when generating reports

- serenity-core/src/main/java/net/thucydides/core/ThucydidesSystemProperty.java
- serenity-core/src/main/java/net/thucydides/core/requirements/FileSystemRequirementsTagProvider.java
- serenity-core/src/main/java/net/thucydides/core/requirements/model/cucumber/CucumberParser.java
- serenity-core/src/main/java/net/thucydides/core/util/MockEnvironmentVariables.java
Commit that fixing #131. Also another PR is needed to configure this property in serenity-maven-plugin.
> Added 'feature.file.encoding' system property to specify an encoding of Cucumber files

- build.gradle
- serenity-core/src/main/java/net/thucydides/core/matchers/dates/DateCollectionContainsSameDatesMatcher.java
- serenity-core/src/main/java/net/thucydides/core/matchers/dates/DateMatcherFormatter.java
- serenity-core/src/main/java/net/thucydides/core/matchers/dates/DateTimeCollectionContainsSameDatesMatcher.java
- serenity-core/src/main/java/net/thucydides/core/reports/html/Formatter.java
- serenity-core/src/main/java/net/thucydides/core/util/PropertiesFileLocalPreferences.java
- serenity-core/src/test/groovy/net/thucydides/core/reports/html/WhenFormattingDataForTheHTMLReports.groovy
- serenity-core/src/test/groovy/net/thucydides/core/webdriver/appium/WhenConfiguringAnAppiumDriver.groovy
- serenity-core/src/test/java/net/thucydides/core/util/WhenReadingEnvironmentVariables.java
fix issue #135 
1) Fixed some tests, that are default locale dependent.
2) Fixed some tests, that are system dependent.
3) Fixed a mistake with wrong paragraph seperator unicode character.
4) Set gradle and java compile encoding directly because it default to system encoding.
> Fixed project build on Windows

- serenity-core/src/main/java/net/thucydides/core/pages/components/Dropdown.java
I'm not sure if there was a reason this was never added. Thought it was worth seeing if you'd accept the pull request.
> feat: Dropdown selectByValue()

- serenity-core/src/main/java/net/serenitybdd/core/photography/ScreenshotNegative.java
Replace usage of java Optional with Guava optional
> Maintain JDK7 compatibility

- serenity-report-resources/src/main/resources/freemarker/components/test-outcomes.ftl
Problem:
gradle clean test integrationTests install fails. 
Reason:
error in serenity-report-resources/src/main/resources/freemarker/components/test-outcomes.ftl
Solution:
updating serenity-report-resources/src/main/resources/freemarker/components/test-outcomes.ftl
> Pull requst for fix build fail 

- serenity-core/src/main/java/net/thucydides/core/annotations/Screenshots.java
- serenity-core/src/main/java/net/thucydides/core/model/ScreenshotPermission.java
- serenity-core/src/main/java/net/thucydides/core/model/TakeScreenshots.java
- serenity-core/src/test/groovy/net/thucydides/core/model/WhenDecidingWhetherToTakeScreenshots.groovy
Here is update for #188 issue
Added feature for disabling screenshots during test.
> Pull request for 188_issue: new level of take screenshots configuration added

- build.gradle
Problem:
in #216 issue reported about some problems during jbehave build. 
Reason:
nothing important, but some classes was refactored in serenityc-core. Also it would be better update mockito to last version
Solution:
update of mockito to last version.
> 216_issue: update versions

- serenity-rest-assured/src/main/java/net/serenitybdd/rest/SerenityRest.java
Reverts serenity-bdd/serenity-core#210. It seems that something was not committed.
> Revert "Pull request for updating SerenityRest to log all types of input"

- gradle.properties
Updates config to build subprojects in parallel
Build speed will be much faster, in 2-3 times.
Run build of this module
N/A
N/A
N/A
N/A
> Updating config to build subprojects in parallel

- gradle.properties
Updates config to build subprojects in parallel
Build speed will be much faster, in 2-3 times.
Run build of this module
N/A
N/A
N/A
N/A
> Updated org.gradle.workers.max value to reduce memory usage

- build.gradle
- serenity-gradle-plugin/src/test/groovy/net/serenitybdd/plugins/gradle/WhenUsingTheGradlePlugin.groovy
Update selenium version to 2.50.1 
Update selenium version to 2.50.1 
N/A
N/A
N/A
#282
N/A
> Upgrading selenium version to 2.50.1

- .gitattributes
Reverts serenity-bdd/serenity-core#293
> Revert "Updating gitattributes not to update chromedriver and woff files"

- .gitattributes
Added gitattributes. Should not generate any "new files" on Snap CI
> Added gitattributes

- serenity-smoketests/pom.xml
Updating smoke-test to use latest serenity-core and serenity maven
> Updating smoke-test to use latest serenity-core and serenity maven

- serenity-core/src/test/groovy/net/thucydides/core/pages/WhenDelegatingWebElements.groovy
> Updating test style

- CHANGELOG.md
Update change log for serenity core
New change log will be available 
you can open this file and github should render it
N/A
N/A
N/A
N/A
> Change log generated for all releases

- CONTRIBUTING.md
- README.markdown
Updated contributing guide
Added commits messages examples and pull requests name convention
During creating pull request or issue you will see splash window
N/A
N/A
N/A
N/A
> Updated contiributing guide - explaned multiline commits and pull requests name convention

- build.gradle
- serenity-core/build.gradle
Updated jbehave to 4.0.5
Updated jbehave to latest version 4.0.5
During executing tests with jbehave new version should be used
N/A
N/A
serenity-bdd/serenity-documentation/issues/60
relevant pull requests: serenity-bdd/serenity-jbehave/pull/47
N/A
> Updated jbehave to 4.0.5

- serenity-core/src/main/java/net/thucydides/core/model/TestOutcome.java
Updated method to print exception i fit will appear
If during serialization some exception will appear it should be missed
N/A
N/A
N/A
#302
N/A
> Updated method to print exception if it will appear

- serenity-core/src/test/groovy/net/serenitybdd/core/photography/integration/WhenAPhotographerTakesLotsOfScreenshots.groovy
Updating test to fail if darkroom fail in parallel screenshot taking
Build fail if bug exists
build should be executed
N/A
N/A
#294
N/A
> Updated test to check how darkroom works in parallel screenshot taking

- serenity-core/build.gradle
Updated appium java client to 3.3.0
It should be possible to use appium with latest version
N/A
N/A
N/A
#235
N/A
> Updated appium java client to 3.3.0

- serenity-junit/src/test/groovy/net/serenitybdd/junit/finder/WhenRunningADataDrivenTestScenarioWithQualifier.groovy
Updated name of test method for Qualifier tests
> Updated name of test method for Qualifier tests

- serenity-core/src/main/java/net/serenitybdd/core/photography/PageSourceRecorder.java
- serenity-core/src/main/java/net/serenitybdd/core/photography/PhotoSession.java
- serenity-core/src/main/java/net/thucydides/core/webdriver/WebDriverFactory.java
- serenity-core/src/test/groovy/net/serenitybdd/core/photography/WhenTakingScreenshotsFromBrowserWithoutTakingScreenshotAbility.groovy
- serenity-core/src/test/groovy/net/serenitybdd/core/photography/WhenTakingScreenshotsFromDiedBrowser.groovy
Updated making screenshots for browsers without such abbility
If HTML Unit is used all should works fine. Before this fix this bug brake tests execution: https://code.google.com/p/selenium/issues/detail?id=1361
Html Unit can be used in test 
N/A
N/A
#218
N/A
> Updated making screenshots for browsers without such abbility

- serenity-core/src/main/java/net/thucydides/core/steps/StepFactory.java
- serenity-core/src/main/java/net/thucydides/core/steps/construction/StepLibraryConstructionStrategy.java
- serenity-core/src/test/groovy/net/serenitybdd/core/steps/WhenInstantiatingAnInstrumentedStepLibrary.groovy
Fixed initialization of step classes with multiple constructors
Should be possible to use step classes with multiple constructors
Some test class should be created with multiple constructor
N/A
N/A
#388
N/A
> Fixed initialization of step classes with multiple constructors

- serenity-core/src/test/groovy/net/thucydides/core/model/WhenExtractingTagsFromTestOutcomes.groovy
see  https://github.com/serenity-bdd/serenity-cucumber/issues/19
added test
> avoid duplicated test outcome in reports :

- serenity-core/src/test/java/net/thucydides/core/reports/integration/WhenGeneratingAnXMLReport.java
> Avoid duplicated test outcome in reports

- serenity-core/src/test/java/net/thucydides/core/reports/integration/WhenGeneratingAnXMLReport.java
Reverts serenity-bdd/serenity-core#401
> Revert "Avoid duplicated test outcome in reports"

- serenity-core/src/main/java/net/thucydides/core/ThucydidesSystemProperty.java
- serenity-core/src/main/java/net/thucydides/core/statistics/service/FeatureStoryTagProvider.java
- serenity-core/src/test/groovy/net/thucydides/core/reports/WhenManagingTestResultTags.groovy
- serenity-core/src/test/groovy/net/thucydides/core/reports/adaptors/specflow/WhenLoadingSpecflowLogOutputAsTestOutcomes.groovy
- serenity-core/src/test/groovy/net/thucydides/core/reports/json/WhenStoringTestOutcomesAsJSON.groovy
- serenity-core/src/test/groovy/net/thucydides/core/tags/WhenFindingTestOutcomeTags.groovy
Reverts serenity-bdd/serenity-core#400
> Revert "set property "use.test.case.for.story.tag = false" by default"

- serenity-core/src/main/java/net/thucydides/core/ThucydidesSystemProperty.java
- serenity-core/src/main/java/net/thucydides/core/model/TestOutcome.java
- serenity-core/src/main/java/net/thucydides/core/reports/xml/TestOutcomeConverter.java
- serenity-core/src/main/java/net/thucydides/core/statistics/service/ClasspathTagProviderService.java
- serenity-core/src/main/java/net/thucydides/core/statistics/service/FeatureStoryTagProvider.java
- serenity-core/src/main/java/net/thucydides/core/statistics/service/JUnitTagProviderStrategy.java
- serenity-core/src/main/java/net/thucydides/core/statistics/service/TagProviderService.java
- serenity-core/src/main/java/net/thucydides/core/statistics/service/TagProviderStrategy.java
- serenity-core/src/main/java/net/thucydides/core/steps/BaseStepListener.java
- serenity-core/src/main/java/net/thucydides/core/steps/StepEventBus.java
- serenity-core/src/main/resources/META-INF/services/net.thucydides.core.statistics.service.TagProviderStrategy
- serenity-core/src/test/groovy/net/thucydides/core/reports/WhenManagingTestResultTags.groovy
- serenity-core/src/test/groovy/net/thucydides/core/reports/adaptors/specflow/WhenLoadingSpecflowLogOutputAsTestOutcomes.groovy
- serenity-core/src/test/groovy/net/thucydides/core/reports/json/WhenStoringTestOutcomesAsJSON.groovy
- serenity-core/src/test/groovy/net/thucydides/core/requirements/WhenUsingACustomRequirementsProvider.groovy
- serenity-core/src/test/groovy/net/thucydides/core/tags/WhenFindingTestOutcomeTags.groovy
- serenity-core/src/test/groovy/net/thucydides/core/webdriver/integration/WhenDeserializingJSONObjects.groovy
- serenity-core/src/test/java/net/thucydides/core/reports/integration/WhenGeneratingAnXMLReport.java
- serenity-core/src/test/java/net/thucydides/core/reports/integration/WhenReadingAnXMLReport.java
- serenity-core/src/test/java/net/thucydides/core/statistics/service/WhenFindingTagsForATestOutcome.java
- serenity-junit/src/main/java/net/thucydides/junit/listeners/JUnitStepListener.java
TestOutcome should store the testSource
> https://github.com/serenity-bdd/serenity-core/issues/406

- .travis.yml
- serenity-core/src/main/java/net/thucydides/core/webdriver/WebDriverFactory.java
- serenity-core/src/test/java/net/serenitybdd/core/webdriver/integration/WhenInstanciatingAAppiumDriver.java
> Omit resizing on appium

- serenity-core/src/main/java/net/thucydides/core/model/TestOutcome.java
- serenity-core/src/main/java/net/thucydides/core/reports/xml/TestOutcomeConverter.java
- serenity-core/src/main/java/net/thucydides/core/statistics/service/ClasspathTagProviderService.java
- serenity-core/src/main/java/net/thucydides/core/statistics/service/JUnitTagProviderStrategy.java
- serenity-core/src/main/java/net/thucydides/core/statistics/service/TagProviderService.java
- serenity-core/src/main/java/net/thucydides/core/statistics/service/TagProviderStrategy.java
- serenity-core/src/main/java/net/thucydides/core/steps/BaseStepListener.java
- serenity-core/src/main/java/net/thucydides/core/steps/StepEventBus.java
- serenity-core/src/main/resources/META-INF/services/net.thucydides.core.statistics.service.TagProviderStrategy
- serenity-core/src/test/groovy/net/thucydides/core/reports/json/WhenStoringTestOutcomesAsJSON.groovy
- serenity-core/src/test/groovy/net/thucydides/core/requirements/WhenUsingACustomRequirementsProvider.groovy
- serenity-core/src/test/groovy/net/thucydides/core/webdriver/integration/WhenDeserializingJSONObjects.groovy
- serenity-core/src/test/java/net/thucydides/core/reports/integration/WhenGeneratingAnXMLReport.java
- serenity-core/src/test/java/net/thucydides/core/reports/integration/WhenReadingAnXMLReport.java
- serenity-core/src/test/java/net/thucydides/core/statistics/service/WhenFindingTagsForATestOutcome.java
- serenity-junit/src/main/java/net/thucydides/junit/listeners/JUnitStepListener.java
Including TestOutcome in testSource
TestOutcome included in testSource
N/A
N/A
N/A
#406
N/A
> TestOutcome included in testSource

- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/matchers/ConsequenceMatchers.java
Issue #542: Improvements when using net.serenitybdd.screenplay.matchers.ConsequenceMatchers#displays:
- Better mismatch. Previously it would fail as follows as the default behaviour describeMismatch() is to perform toString() on the whole domain object (which may not have a decent toString() override either), not just the field: 
```
Expected: showing 'name' as "Diana"
but: was <net.serenitybdd.screenplay.webtests.model.Customer@24fabd0f>
```
But now the message is as follows:
```
java.lang.AssertionError: 
Expected: to display 'name' as "Diana"
but: displayed  'name' as "Dana"
```
- Unknown field message. Previously it would fail as follows: 
```
Unknown domain field Surname
```
But now the message is as follows:
```
Unknown display field 'Surname'. Must be one of: 'country', 'name'
```
> Issue #542: ConsequenceMatchers: Better mismatch and Unknown field messages

- serenity-core/src/main/java/net/thucydides/core/ThucydidesSystemProperty.java
- serenity-core/src/main/java/net/thucydides/core/webdriver/strategies/ChromeDriverCapabilities.java
Issue #536: Support for webdriver.chrome.binary property
> Issue #536: Support for webdriver.chrome.binary property

- README.markdown
Converted a Yoda-ish sentence about the Contributing document into
something clearer.
> docs: Untangled an unusual sentence structure in the README file.

- build.gradle
- serenity-spring/build.gradle
- serenity-spring/src/main/java/net/serenitybdd/core/di/SpringDependencyInjector.java
- serenity-spring/src/test/java/net/thucydides/junit/spring/SpringBootTestAnnotatedStepLibrary.java
- serenity-spring/src/test/java/net/thucydides/junit/spring/WhenInjectingSpringDependenciesIntoSpringBootTests.java
Support dependency injection for step libraries annotated with
@SpringBootTest (introduced in spring-boot-test 1.4)
To test this feature additional dependency on
spring-boot-test and upgrade to Spring 4.3 is needed.
> #608 @SpringBootTest support

- serenity-core/src/main/java/net/thucydides/core/webdriver/capabilities/BrowserStackRemoteDriverCapabilities.java
Add the capability to set the test name in Browserstack 
We need this as currently the test name set in browserstack is the session ID
> Add BrowserStack test name to compatibilites

- serenity-core/src/main/java/net/thucydides/core/webdriver/WebDriverFacade.java
> Only shutdown fixture services if closing the last tab in a browser

- serenity-core/src/main/java/net/thucydides/core/webdriver/capabilities/ChromePreferences.java
> Issue #887 fix: remove extra point in ChromePreferences getPreparedPropertyKey

- serenity-core/src/main/java/net/thucydides/core/webdriver/redimension/RedimensionStrategy.java
Update RedimensionStrategy.java
Fixed #898
> Fix: Maximize browser with serenity properties

- gradle.properties
Updated to latest Appium Java Client version
https://github.com/appium/java-client/tags
Please review
> updated appium java client version

- gradle.properties
Please review the PR
1. Ran _gradle clean test integrationTests_ , similar to last time FF related test cases are still failing.
Please refer to attached screen shots
Next week, I'll have a look why FF test cases are failing & think how to add appium related integration test cases to this suite
2. These changes should fix iOS related bug filed by me.
> updated versions of selenium & appium

- serenity-appium/README.md
- serenity-appium/pom.xml
- serenity-appium/serenity.properties
- serenity-appium/src/test/java/integration/WordPressAppTest.java
- serenity-appium/src/test/java/integration/cucumer/WordPressLoginScenarioSteps.java
- serenity-appium/src/test/java/integration/pages/MobilePageObject.java
- serenity-appium/src/test/java/integration/pages/WordPressLoginPage.java
- serenity-appium/src/test/java/integration/resources/features/invalid_login.feature
- serenity-appium/src/test/java/integration/serenitySteps/WordPressLoginSteps.java
@wakaleo please review the first commit.
> serenity+appium integration iOS platform first test case

- serenity-core/src/main/java/net/serenitybdd/core/pages/WebElementFacade.java
- serenity-core/src/main/java/net/serenitybdd/core/pages/WebElementFacadeImpl.java
- serenity-core/src/main/java/net/thucydides/core/annotations/locators/SmartFieldDecorator.java
Update according to https://github.com/SeleniumHQ/selenium/commit/b37c27b4c62c4ba336a3a96b125f86ad0f15f04b
Fixes #1012
> Update Locatable to interactions package

- serenity-core/src/main/java/net/serenitybdd/core/pages/WebElementFacadeImpl.java
- fixes compilation error in WebElementFacadeImpl
> #1027 - remove spurious characters from last commit 

- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/Hover.java
I found this screenplay construct handy and thought of sharing it here in order not having to re-write   it manually in every project.
What do you think?
> Adding 'Hover over' Interaction in Screenplay Webdriver

- serenity-report-resources/src/main/resources/report-resources/css/core.css
Increased the margin-left px to 30px from 15px.
> Updated core.css

- serenity-core/src/main/java/net/thucydides/core/model/TitleBuilder.java
- serenity-core/src/test/groovy/net/thucydides/core/model/WhenBuildingATitle.groovy
Add edge icon for context 'edge'
> Add edge icon for context 'edge'

- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/targets/ByTarget.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/targets/IFrame.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/targets/IFrameSwitcher.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/targets/Target.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/targets/TargetBuilder.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/targets/TargetFactory.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/targets/TargetResolver.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/targets/XPathOrCssTarget.java
- serenity-screenplay-webdriver/src/test/java/net/serenitybdd/screenplay/webtests/integration/WhenDanaBrowsesTheWeb.java
- serenity-screenplay-webdriver/src/test/java/net/serenitybdd/screenplay/webtests/model/BankAccountBalances.java
- serenity-screenplay-webdriver/src/test/java/net/serenitybdd/screenplay/webtests/model/BankBalances.java
- serenity-screenplay-webdriver/src/test/java/net/serenitybdd/screenplay/webtests/pages/BankAccountBalanceTargets.java
- serenity-screenplay-webdriver/src/test/java/net/serenitybdd/screenplay/webtests/pages/BankAccountEntry.java
- serenity-screenplay-webdriver/src/test/java/net/serenitybdd/screenplay/webtests/questions/BankBalanceQuestion.java
- serenity-screenplay-webdriver/src/test/resources/sample-web-site/profile-bank-balance.html
- serenity-screenplay-webdriver/src/test/resources/sample-web-site/profile-bank.html
This replaces PR #533 with newly rebased version. Still very much a requirement for merging, as we can only use 'this' version of serenity on my client's project.
> Issue #532: feat: added support for iframe switching

- serenity-rest-assured/src/main/java/net/serenitybdd/rest/decorators/request/RequestSpecificationDecorated.java
- serenity-rest-assured/src/test/groovy/net/serenitybdd/rest/WhenRecordGetRequestsWithSerenityRest.groovy
include query in report also when filters are used
> fix for https://github.com/serenity-bdd/serenity-core/issues/1149

- serenity-core/src/main/java/net/serenitybdd/core/pages/PageObject.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/targets/ByTarget.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/targets/IFrame.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/targets/IFrameSwitcher.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/targets/Target.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/targets/TargetBuilder.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/targets/TargetFactory.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/targets/TargetResolver.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/targets/XPathOrCssTarget.java
- serenity-screenplay-webdriver/src/test/java/net/serenitybdd/screenplay/webtests/integration/WhenDanaBrowsesTheWeb.java
- serenity-screenplay-webdriver/src/test/java/net/serenitybdd/screenplay/webtests/model/BankAccountBalances.java
- serenity-screenplay-webdriver/src/test/java/net/serenitybdd/screenplay/webtests/model/BankBalances.java
- serenity-screenplay-webdriver/src/test/java/net/serenitybdd/screenplay/webtests/pages/BankAccountBalanceTargets.java
- serenity-screenplay-webdriver/src/test/java/net/serenitybdd/screenplay/webtests/pages/BankAccountEntry.java
- serenity-screenplay-webdriver/src/test/java/net/serenitybdd/screenplay/webtests/questions/BankBalanceQuestion.java
- serenity-screenplay-webdriver/src/test/resources/sample-web-site/index.html
- serenity-screenplay-webdriver/src/test/resources/sample-web-site/profile-bank-balance.html
- serenity-screenplay-webdriver/src/test/resources/sample-web-site/profile-bank.html
- serenity-screenplay-webdriver/src/test/resources/sample-web-site/profile.html
- Fixed problem with integration tests not passing, Pre-merge job can be seen [here](http://34.248.197.198:8080/blue/organizations/jenkins/integration-tests-copy/detail/integration-tests-copy/31/tests).
- Changed IFrame definition to accept path of Locators for added flexibility (previously only supported names)
- IFrame now represented as Optional throughout
> FEAT: support for iframe switching within Screenplay

- serenity-core/src/main/java/net/serenitybdd/core/annotations/locators/SmartAnnotations.java
allow numerical id values in SmartAnnotation
> https://github.com/serenity-bdd/serenity-core/issues/1177

- serenity-core/src/main/java/net/serenitybdd/core/photography/PageSourceRecorder.java
https://github.com/serenity-bdd/serenity-core/issues/1247
> Catch WebDriverExceptions while getting the pagesource

- serenity-model/src/main/java/net/thucydides/core/requirements/FileSystemRequirementsTagProvider.java
Also make sure that the returned list is not modified by anyone
https://github.com/serenity-bdd/serenity-core/issues/1291
> Add double-checked locking for requirements

- serenity-core/src/main/java/net/serenitybdd/core/photography/PageSourceRecorder.java
- serenity-core/src/main/java/net/serenitybdd/core/photography/PhotoSession.java
https://github.com/serenity-bdd/serenity-core/issues/1333
> catch all exceptions while getting screenshots or page sources

- serenity-core/src/test/groovy/net/thucydides/core/util/WhenDisplayingTagNamesInAReadableForm.groovy
- serenity-core/src/test/java/net/thucydides/core/pages/WhenManagingTheInternalClock.java
- serenity-model/src/main/java/net/serenitybdd/core/time/Stopwatch.java
- serenity-model/src/main/java/net/thucydides/core/ThucydidesSystemProperty.java
- serenity-model/src/main/java/net/thucydides/core/util/Inflection.java
- serenity-model/src/main/java/net/thucydides/core/util/Inflector.java
- serenity-reports/src/main/java/net/thucydides/core/reports/html/HtmlAggregateStoryReporter.java
- this are the core changes required by https://github.com/serenity-bdd/serenity-cucumber/pull/164
> feat #1344 - Support for running Cucumber Serenity in parallel batches

- serenity-core/src/main/java/net/serenitybdd/core/webdriver/driverproviders/ChromeDriverCapabilities.java
- serenity-core/src/test/groovy/net/thucydides/core/webdriver/chrome/WhenPassingChromeExperimentalOptionsToWebdriver.groovy
Hey @wakaleo, thanks for the quick reply.
It is my first time contributing on a big project, if you need any changes please let me know
> feat: Add Chrome experimental options 

- serenity-core/src/main/java/net/serenitybdd/core/di/WebDriverInjectors.java
- serenity-gradle-plugin/src/main/groovy/net/serenitybdd/plugins/gradle/SerenityPlugin.groovy
- serenity-model/src/main/java/net/thucydides/core/guice/Injectors.java
> Gradle plugin class SerenityPlugin is not thread-safe

- serenity-core/src/main/java/net/serenitybdd/core/pages/WebElementFacadeImpl.java
- serenity-core/src/main/java/net/serenitybdd/core/pages/WebElementState.java
- serenity-core/src/main/java/net/thucydides/core/webdriver/stubs/WebElementFacadeStub.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/matchers/WebElementStateMatchers.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/matchers/statematchers/MissingWebElement.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/matchers/statematchers/isClickableMatcher.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/questions/UnresolvedTargetWebElementState.java
- serenity-screenplay-webdriver/src/test/java/net/serenitybdd/screenplay/webtests/integration/WhenDanaChecksTheStateOfWebElements.java
> Adds the isCLickable method to the statematchers

- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/type/TypeValueIntoTarget.java
Issue Ticket: https://github.com/serenity-bdd/serenity-core/issues/1475
This fix was done to adapt to the newly added conditional statements in Selenium's RemoteWebElement class.
> Fix issue where sendKey() returns an IllegalArgumentException.

- serenity-screenplay/src/main/java/net/serenitybdd/screenplay/Actor.java
- serenity-screenplay/src/main/java/net/serenitybdd/screenplay/NoMatchingAbilityException.java
- serenity-screenplay/src/main/java/net/serenitybdd/screenplay/UseAnAbility.java
- serenity-screenplay/src/test/groovy/net/serenitybdd/screenplay/WhenActorsHaveAbilities.groovy
Example Usage: `UseAnAbility.of(actor).that(CanLevitate.class).hover()`
> #1493 add factory to access ability by implemented interface

- serenity-core/src/main/java/net/serenitybdd/core/webdriver/driverproviders/ChromeDriverCapabilities.java
Reverts serenity-bdd/serenity-core#1470
> Revert "Address #1486 - Saucelabs/Chrome"

- serenity-model/src/main/java/net/thucydides/core/requirements/FileSystemRequirementsTagProvider.java
- serenity-model/src/main/java/net/thucydides/core/requirements/model/cucumber/CucumberParser.java
https://github.com/serenity-bdd/serenity-core/issues/1533
> fix for jdk11/gradle5

- serenity-core/src/main/java/net/serenitybdd/core/pages/WebElementFacade.java
- serenity-core/src/main/java/net/serenitybdd/core/pages/WebElementFacadeImpl.java
- serenity-core/src/main/java/net/thucydides/core/webdriver/stubs/WebElementFacadeStub.java
> Implemented withTimeoutOf(Duration) for WebElementStub

- serenity-core/src/main/java/net/serenitybdd/core/pages/PageObject.java
- serenity-core/src/main/java/net/thucydides/core/webdriver/WebDriverFacade.java
@wakaleo just tried to fix that `getDriver() instanceof WebElementFacade` and it actually fixes the issue without adding `Interactive` to `WebDriverFacade`
> Corrected fix for https://github.com/serenity-bdd/serenity-core/issues/1584

- serenity-model/src/main/java/net/thucydides/core/requirements/model/cucumber/CucumberParser.java
- serenity-model/src/main/java/net/thucydides/core/util/VersionProvider.java
- serenity-model/src/test/java/net/thucydides/core/util/VersionProviderTest.java
if archive name ends with  "all" -  gets the version name in the old way from the property file
> get version number from loaded code source resource name

- serenity-model/src/main/java/net/thucydides/core/requirements/model/RequirementsConfiguration.java
- serenity-model/src/test/groovy/net/thucydides/core/model/WhenBuildCucumberRequirementsConfigurationOnClasspath.groovy
Fix for issue #1644 and add appropriate test for `RequirementsConfiguration` constructor.
> fix: issue #1644

- serenity-core/src/test/resources/sample-big-report/nivo-slider/3.2/nivo-slider.css
https://github.com/serenity-bdd/serenity-core/issues/1667
> Don't make description hide the top of the screenshot

- serenity-model/src/main/java/net/thucydides/core/model/TestStep.java
- serenity-report-resources/src/main/resources/freemarker/default.ftl
> Thumbnail links to screenshots

- serenity-report-resources/src/main/resources/freemarker/default.ftl
> fixes screenshot numbering for datadriven tests

- serenity-core/src/main/java/net/serenitybdd/core/webdriver/driverproviders/ChromeDriverCapabilities.java
Please let me know what I need to do to get this MR accepted.
> make WEBDRIVER_CHROME_BINARY work

- serenity-report-resources/src/main/resources/freemarker/default.ftl
Hello @ShaunyPrawn - good news - I've built collapsible_nested_steps branch locally and I can't see anything wrong with the expansion now, whereas I was having lots of trouble before:
Thanks very much for this feature - I can now close #1004 😃
> fix: #1759 Error with expandable behavior - updated substep HTML ID

- serenity-report-resources/src/main/resources/freemarker/libraries/chartist.ftl
- serenity-report-resources/src/main/resources/freemarker/libraries/font-awesome.ftl
> Add css mime types

- serenity-mobile-screenplay-example/src/test/java/com/serenity/cucumber/stepdefs/StepDefs.java
- serenity-mobile-screenplay-example/src/test/resources/features/record_notes/add_new_items_to_the_note_list.feature
- Remove unnecessary steps
- Update scenario
> fix: the application starts 2 times in cucumber profile

- serenity-gradle-plugin/src/main/groovy/net/serenitybdd/plugins/gradle/SerenityPlugin.groovy
> attempt to fix #1910

- serenity-stats/src/main/kotlin/net/serenitybdd/reports/model/CustomReportFields.kt
- serenity-stats/src/test/kotlin/net/serenitybdd/reports/model/WhenConfiguringCustomReportFields.kt
This fix one part of the #1916
> Add environment support for custom report fields

- serenity-model/src/main/java/net/thucydides/core/ThucydidesSystemProperty.java
Fix https://github.com/serenity-bdd/serenity-core/issues/2019
> Fix JavaDoc for SERENITY_JQUERY_INTEGRATION

- serenity-model/src/main/java/net/thucydides/core/requirements/model/cucumber/CucumberParser.java
https://github.com/serenity-bdd/serenity-core/issues/2023
> fix missing requirements when using example tags

- serenity-browserstack/src/main/java/net/serenitybdd/browserstack/BeforeABrowserStackScenario.java
> Fixed browserstack properties

- serenity-core/src/main/java/net/serenitybdd/core/pages/WebElementExpectations.java
#2040 WebElementExpectations should use WebElementFacade instead of WebElementFacadeImpl
> #2040 WebElementExpectations should use WebElementFacade

- serenity-model/src/main/java/net/thucydides/core/util/PropertiesFileLocalPreferences.java
> fix: replaced "environmentVariables.optionalProperty(...)" with "optionalEnvironmentVariable(...)

- serenity-screenplay/src/main/java/net/serenitybdd/screenplay/conditions/PerformBasedOnAbility.java
- serenity-screenplay/src/main/java/net/serenitybdd/screenplay/conditions/PossibleAction.java
- serenity-screenplay/src/test/java/net/serenitybdd/screenplay/shopping/WhenTasksAreRunBasedOnAbilityPresent.java
relates to #2080 
interface to map actions to abilities so different actors can use the same steps
do you want something like that?
if yes, like this? or something like `actor.attemptsTo(perform).givenTheyCan(abilityClazz)`?
> basically switch as performable 

- serenity-rest-assured/src/main/java/net/serenitybdd/rest/decorators/request/RequestSpecificationDecorated.java
- serenity-screenplay-rest/src/test/java/net/serenitybdd/screenplay/rest/examples/WhenUsingSessionFilterRegressionTest.java
no need to decorate as we do nothing with the decorated RequestSpecification,
fixes #2089
> applying filter changed reference to RequestSpecification,

- serenity-single-page-report/src/main/resources/templates/email/serenity-summary-report-inlined.html
This will resolve the distortion issues for gmail and rest others are not impacted.
I had raised issue #2109 for showing the distortion.
> Resolve distortion for gmail in emailable report

- serenity-single-page-report/src/main/resources/templates/email/serenity-summary-report-inlined.html
Please refer issue #2109 for more details
> Fix color coding for summary in single page html report

- serenity-model/src/main/java/net/thucydides/core/util/Inflector.java
> updated link to Inflector class documentation

- serenity-core/src/main/java/net/thucydides/core/steps/StepInterceptor.java
- serenity-screenplay/src/test/groovy/net/serenitybdd/screenplay/WhenInstrumentingTasks.groovy
- serenity-screenplay/src/test/java/net/serenitybdd/screenplay/Eats.java
- serenity-screenplay/src/test/java/net/serenitybdd/screenplay/EatsAMango.java
Marking with IsHidden still adds the step into the report as mentioned in #1525
Opened this PR to fix that
> don't report Performable with IsHidden

- serenity-core/src/main/java/net/serenitybdd/core/pages/WebElementFacadeImpl.java
> fix issue #2134 ?

- serenity-screenplay/src/main/java/net/serenitybdd/screenplay/conditions/PerformBasedOnAbility.java
I don't feel ok with promoting this use of abilities. It shouldn't be in the framework imho.
I hope nobody uses this :) i'd like to remove it in the version after the next.
> this was a bad idea

- serenity-core/src/main/java/net/serenitybdd/core/exceptions/NoSuchElementException.java
- serenity-core/src/main/java/net/serenitybdd/core/pages/WebElementFacadeImpl.java
> fix issue #2138

- CONTRIBUTING.md
Couple of spelling mistakes have been corrected.
> docs: correcting typos

- serenity-model/src/main/java/net/serenitybdd/core/environment/EnvironmentSpecificConfiguration.java
- serenity-model/src/test/groovy/net/serenitybdd/core/environment/WhenDefiningBaseUrlsForDifferentEnvironments.groovy
- Fixing the infinitive loop when a serenity env property value is built by substitution of several other env properties
- Adding unit tests
> Fixing the infinitive loop when from issue #2207

- serenity-model/src/main/java/net/thucydides/core/model/LastElement.java
- serenity-model/src/main/java/net/thucydides/core/model/Story.java
Fix the problem with duplicate reporting that occurs when the ".feature" files are placed directly under the "features" directory root.
> fix for https://github.com/serenity-bdd/serenity-cucumber/issues/143

- build.gradle
- gradle.properties
Apache commons-text upgrade to 1.8.
> Apache commons-text upgrade to 1.8. Removed reference to 1.2

- README.md
Updated README.md after release
> Updated README.md after release

- gradle.properties
- serenity-core/src/test/java/net/thucydides/core/webdriver/WhenObtainingTheOutputDirectory.java
- serenity-sample-alternative-resources/build.gradle
JBehave version upgrade to 4.7
Unified version of JBehave in whole project
> JBehave version upgrade to 4.7

- gradle.properties
XStream version upgrade to 1.4.13
> XStream version upgrade to 1.4.13

- serenity-core/src/main/java/net/serenitybdd/core/pages/WebElementFacadeImpl.java
> fix: #2275 NPE

- serenity-model/src/main/java/net/thucydides/core/reflection/StackTraceAnalyser.java
* no tests adjusted as I did not find tests for the different cases in StackTraceAnalyser
> Ignore stacktrace element for inner interfaces and inner or anonymous classes without a superclass (#2229)

- serenity-rest-assured/src/main/java/net/serenitybdd/rest/SerenityRest.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/decorators/ResponseSpecificationDecorated.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/decorators/request/RequestSpecificationDecorated.java
- serenity-screenplay-rest/src/main/java/net/serenitybdd/screenplay/rest/interactions/RestInteraction.java
:bug: FIX #2029
:ambulance: FIX and error in latest versions, when using enableLoggingOfRequestAndResponseIfValidationFails method, possible FIX for #2310 
@wakaleo let me know if u have comments.
> Add support to hide rest queries using screenplay

- serenity-rest-assured/src/main/java/net/serenitybdd/rest/decorators/ResponseDecorated.java
> Add missing as() overrides to ResponseDecorated

- serenity-core/src/main/java/net/serenitybdd/core/pages/WebElementFacadeImpl.java
4 hours lost today, until I found this :(
> textarea also has a 'value'

- serenity-core/src/main/java/net/serenitybdd/core/pages/WebElementFacadeImpl.java
I am ashamed for my previous https://github.com/serenity-bdd/serenity-core/pull/2304
This is the correct way of checking for "value" attribute.
> correct the check for value attribute

- serenity-junit/src/main/java/net/serenitybdd/junit/runners/SerenityRunner.java
this PR addresses the issue #2330
> #2330: fix the reference to driver in steps when running parallel tests

- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/Switch.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/SwitchToNewWindow.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/SwitchToWindowTitle.java
I am submitting this MR, because:
1. I find myself constantly rewriting these and I think others might find them useful, and
2. I would welcome feedback on my code style. :)
> add new Switch Tasks

- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/RightClick.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/RightClickOnElement.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/RightClickOnTarget.java
> add right-click action

- serenity-model/src/main/java/net/thucydides/core/logging/ConsoleHeading.java
- serenity-model/src/main/java/net/thucydides/core/logging/ConsoleLoggingListener.java
* Possibility to don't print welcome banner was added
* Dead code was removed
> Don't print welcome banner if serenity.console.banner is set to NONE

- serenity-core/src/main/java/net/thucydides/core/steps/BaseStepListener.java
> Fix NullPointerException caused by call to Serenity.takeScreenshot()

- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/OpenPageFromClass.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/OpenPageFromClassWithParameters.java
feat: Add webdriver screenplay action to open pages with parameters.
> Add possibility to open pages with parameters

- serenity-shutterbug1x/readme.md
- serenity-shutterbug1x/src/main/java/net/serenitybdd/screenshots/shutterbug/Shutterbug1XScreenShooter.java
Read Shutterbug parameters as properties instead of system values to fix #2554.
> Fix problems with taking full screen screenshots

- serenity-screenplay-playwright/pom.xml
- serenity-screenplay-playwright/src/main/java/net/serenitybdd/screenplay/playwright/PlayWrightConfigurationProperties.java
- serenity-screenplay-playwright/src/main/java/net/serenitybdd/screenplay/playwright/abilities/BrowseTheWebWithPlaywright.java
- serenity-screenplay-playwright/src/main/java/net/serenitybdd/screenplay/playwright/interactions/WaitFor.java
- Add possibility to trace
- Upgrade Playwright.
- Reset currentPage and currentContext after closing Playwright
- Enable BROWSER_CHANNEL in launchOptions.
- Fix step name for WaitFor action
> Playwright integration

- serenity-single-page-report/src/main/resources/templates/email/serenity-summary-report-inlined.html
- serenity-single-page-report/src/test/kotlin/net/serenitybdd/reports/email/WhenGeneratingAnEmailableReport.kt
> use full url for view full report link on summary page

- serenity-core/src/main/java/net/serenitybdd/core/pages/WebElementFacadeImpl.java
> :ambulance: Fix an error when checking if an element has value attribute on Appium

- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/questions/UnresolvedTargetWebElementState.java
- serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/questions/WebElementQuestion.java
- serenity-screenplay/src/main/java/net/serenitybdd/screenplay/Actor.java
- serenity-screenplay/src/main/java/net/serenitybdd/screenplay/ErrorTally.java
- serenity-screenplay/src/main/java/net/serenitybdd/screenplay/EventualConsequence.java
- serenity-screenplay/src/main/java/net/serenitybdd/screenplay/questions/QuestionWithDefinedSubject.java
@wakaleo I'm not sure since when, but soft-assertions inside `actor.should()`  stop working when using WebElementQuestions, more specific `QuestionWithDefinedSubject`, this was because the `attemptsTo` method was called without `ignore exceptions `mode, the same applies to eventual consequences.
I also add a way to try to improve the text displayed when an element was not found in screenplay.
> :ambulance: Soft-assertions were no working

- serenity-core/src/main/java/net/thucydides/core/webdriver/WebdriverInstances.java
FIX #2805
@wakaleo after merged, can I ask you to generate a new release?
> :ambulance: Clear active driver for screenplay when an error happens

- serenity-maven-plugin/src/main/java/net/serenitybdd/maven/plugins/SerenityAggregatorMojo.java
update class loader in reportFrom method
> feat: update class loader in reportFrom method for maven plugin

- serenity-core/src/main/java/net/serenitybdd/core/webdriver/driverproviders/RemoteDriverProvider.java
Explained here https://medium.com/alphadev-thoughts/are-you-using-optional-orelse-wrong-4f39585a19da
> #2947 Fixed remote driver name environment configuration resolution

- serenity-core/src/main/java/net/serenitybdd/core/photography/WebDriverPhotoLens.java
- serenity-model/src/main/java/net/thucydides/core/ThucydidesSystemProperty.java
#2972 & #2990
changing the method to check is alert displayed or not, without driver.switchTo that cause those issues
> fixing issue #2972 & #2990

- serenity-junit5/src/main/java/net/serenitybdd/junit5/datadriven/JUnit5CSVTestDataSource.java
> fix: resolves issue with data table not populating when using a csvfilesource on windows

- serenity-junit5/src/main/java/net/serenitybdd/junit5/JUnit5DataDrivenAnnotations.java
- serenity-junit5/src/main/java/net/serenitybdd/junit5/datadriven/JUnit5CSVTestDataSource.java
#3007 
Another small fix, to allow users to use the files in the CsvFileSource annotation.
> Fix junit5csvfilesource

- serenity-report-resources/src/main/resources/freemarker/components/report-data.ftl
- serenity-report-resources/src/main/resources/report-resources/css/core.css
> copy-button for report-data card-body content

- pom.xml
- serenity-core/pom.xml
- serenity-maven-plugin/pom.xml
- serenity-model/pom.xml
- serenity-model/src/main/java/net/thucydides/model/matchers/BeanMatcherAsserts.java
- serenity-model/src/main/java/net/thucydides/model/reports/html/ExampleTable.java
- serenity-model/src/main/java/net/thucydides/model/reports/xml/TestOutcomeConverter.java
- serenity-model/src/main/java/net/thucydides/model/requirements/RequirementsPath.java
- serenity-model/src/main/java/net/thucydides/model/requirements/model/Requirement.java
- serenity-reports/pom.xml
@wakaleo updated some vulnerable dependencies
Build results are same as the previous PR,
1. [CI](https://github.com/dkumarra/serenity-core/actions/runs/5937247243/job/16099290189)
2. [Chrome](https://github.com/dkumarra/serenity-core/actions/runs/5937247242/job/16099289988)
3. [FireFox](https://github.com/dkumarra/serenity-core/actions/runs/5937247230/job/16099289990)
4. [BrowserStack](https://github.com/dkumarra/serenity-core/actions/runs/5937247238/job/16099289982)
5. [SauceLabs](https://github.com/dkumarra/serenity-core/actions/runs/5937247235/job/16099290200)
6. [LambdaTest](https://github.com/dkumarra/serenity-core/actions/runs/5937247233/job/16099290006)
> Updated vulnerable dependencies

- serenity-core/src/main/java/net/thucydides/core/steps/BaseStepListener.java
Fix for adding screenshots using FOR_FAILURES when the assert is in the StepDefinitions.
- Removed the check `shouldTakeEndOfStepScreenshotFor(result)` from the method `takeEndOfStepScreenshotForRecording`.
- Added the method `shouldTakeEndOfStepScreenshot(result)` to the method `takeEndOfStepScreenshotForPlayback`
Above change makes sure a screenshot is always taken (e..g FOR_EACH_ACTION) but within the playback functionality it's checked if the screenshot needs to be added.
- Declared and initialised a list for all screenshots (allScreenshots)
- Declared and initialised a list for used screenshots (usedScreenshots)
- In the`takeEndOfStepScreenshotForPlayback` populate these lists.
- Added a new method `removeUnnecesaryScreenshotsFromOutputDir` which handles the deletion of unused …
> #3334 Fix for screenshots FOR_FAILURES

- serenity-core/src/main/java/net/thucydides/core/steps/StepInterceptor.java
improve reporting for data-driven tests that have failures in an intermediate step
> improve reporting for data-driven tests

- serenity-report-resources/src/main/resources/freemarker/default.ftl
- serenity-report-resources/src/main/resources/freemarker/junit5/default.ftl
- serenity-reports/src/main/java/net/thucydides/core/reports/html/Formatter.java
Reverts serenity-bdd/serenity-core#3524
> Revert "fixing display issues when using <> or \" characters in scenario outline titles / data table values"

- serenity-model/src/main/java/net/thucydides/model/steps/ReplaceField.java
> step message of SelectByValue doesn't report used value

- serenity-cucumber/src/main/java/io/cucumber/core/plugin/FeatureFileLoader.java
- serenity-cucumber/src/main/java/io/cucumber/core/plugin/ScenarioContextParallel.java
- serenity-cucumber/src/main/java/io/cucumber/core/plugin/SerenityReporter.java
- serenity-cucumber/src/main/java/io/cucumber/core/plugin/SerenityReporterParallel.java
This PR is a proposed solution for issue https://github.com/serenity-bdd/serenity-core/issues/3583
> extract scenarioIdFrom functionality

- serenity-rest-assured/src/main/java/net/serenitybdd/rest/SerenityRest.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/filters/FieldsRecordingFilter.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/filters/UpdatingContextFilter.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/utils/RestReportingHelper.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/utils/RestResponseRecordingHelper.java
- serenity-rest-assured/src/main/java/net/serenitybdd/rest/utils/RestRuntimeException.java
This PR should solve the problem https://github.com/serenity-bdd/serenity-core/issues/3608
> unwrap runtime exceptions created by rest when reporting

- serenity-cucumber/src/main/java/io/cucumber/core/plugin/SerenityReporterParallel.java
My solution of issue https://github.com/serenity-bdd/serenity-core/issues/3650
> Set protected access modifier in SerenityReporterParallel initialiseListenersFor

- serenity-core/src/test/java/net/thucydides/core/steps/WhenStepsExtends.java
- serenity-core/src/test/java/net/thucydides/core/steps/samples/ExtendChildScenarioSteps.java
- serenity-core/src/test/java/net/thucydides/core/steps/samples/ExtendParentScenarioSteps.java
- serenity-model/src/main/java/net/thucydides/model/reflection/MethodFinder.java
https://github.com/serenity-bdd/serenity-core/issues/3652#issuecomment-2893568448
> fix/3652 Test step descriptions are not overwritten when extending classes
